# Validate Knowledge Graph Repository

Simple check on kg repo capabilities:
- start with seed id for a given paragraph (mentions greek polis)
- find entities in that paragraph
- find 1st order hops from those entities
- create graph with pyvis

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent / "src"))

In [2]:
from history_book.database.config.database_config import WeaviateConfig
from history_book.database.repositories.book_repository import BookRepositoryManager
from history_book.utils import print_with_wrapping

import pandas as pd

In [3]:

config = WeaviateConfig.from_environment()
mgr = BookRepositoryManager(config)

# Quick counts
print(f"KG Entities:       {mgr.kg_entities.count()}")
print(f"KG Relationships:  {mgr.kg_relationships.count()}")
print(f"KG Graphs:         {mgr.kg_graphs.count()}")

# What graphs do we have?
for g in mgr.kg_graphs.list_all():
    print(f"\n  {g.name} ({g.graph_type}): {g.entity_count} entities, {g.relationship_count} rels, chapters={g.book_chapters}")

KG Entities:       1026
KG Relationships:  1996
KG Graphs:         3

  book3_ch4_5 (book): 487 entities, 998 rels, chapters=['3:4', '3:5']

  book3_ch4 (chapter): 195 entities, 351 rels, chapters=['3:4']

  book3_ch5 (chapter): 344 entities, 647 rels, chapters=['3:5']

In [3]:
# Which graph has this paragraph? Use the merged book graph.
graph_name = "book3_ch0-7"

In [4]:
mgr.kg_entities.search_entities(query_text="Parthia", graph_name=graph_name)

[]

In [5]:
search_res = mgr.kg_entities.search_entities_hybrid(query_text="Parthia", graph_name=graph_name, limit=10)
search_res

[(KGEntity(id='b8b77f5f-8124-4fbc-bcdf-e07d37c24b16', graph_name='book3_ch0-7', name='Ctesiphon', entity_type='place', aliases=[], descriptions=['Capital of Parthia conquered by Trajan.', 'City where Ardashir was crowned king after killing the last king of Parthia.'], occurrence_count=2, book_indices=[3], source_book_chapters=['3:4', '3:5'], source_pages=[346, 389], source_paragraph_ids=['4fe58a41-098d-4d03-bbe0-6867e560a190', '1cfb6550-4c6e-4c63-a181-7dc7a3a15e46'], merged_from_count=2),
  0.5),
 (KGEntity(id='c9dcabf6-21d8-4f49-9061-759f1b7971a7', graph_name='book3_ch0-7', name='Roman legions', entity_type='concept', aliases=['legions'], descriptions=["The military units of Rome that became increasingly professional and were given 'eagles' as standards by Marius.", 'The core military units of the Roman army, numbering twenty-eight after AD 9.'], occurrence_count=2, book_indices=[3], source_book_chapters=['3:4'], source_pages=[334, 359], source_paragraph_ids=['c5114908-0cf5-4856-9b39-929e4fdf65ae', '2cb51a19-36f2-44ce-b833-08d3ecdb40f9'], merged_from_count=2),
  0.5),
 (KGEntity(id='a55b9d44-5e39-43fe-ac2e-da980ef759e9', graph_name='book3_ch0-7', name='Gaul', entity_type='place', aliases=['northern France and Belgium'], descriptions=['Region conquered in 51 BC, ending the Celtic threat.', 'Region conquered by Julius Caesar after a succession of campaigns.', 'A province conquered and commanded by Caesar.', "Region where descendants of Caesar's soldiers were settled in new military colonies.", 'Region invaded by the Vandals and Alans after crossing the Rhine frontier.', 'Region abandoned to the Vandals as Italy was protected.', 'A region where Arian Christianity was dominant.', 'A region lying in the shadow of the Visigoths of Aquitaine after devastation by the Vandals.', 'Region where Clovis conquered lands from the last Roman governors', 'The region over which Clovis became the successor of the Romans.', 'Region where the Franks took up Latin and influenced the local language.'], occurrence_count=11, book_indices=[3], source_book_chapters=['3:4', '3:5'], source_pages=[333, 337, 346, 407, 413, 420, 421, 423], source_paragraph_ids=['64868c1e-59df-41fd-a958-0b160a981112', '523df312-21f4-4e70-ae15-392d3f02f7f9', '27b8d148-81ab-43e5-8077-5a20cd4208d1', '81d9fa5b-1ecf-4ea0-909b-36d40c5d8be7', '76509f09-6b2e-4a35-8d6d-717c200ed38e', '3a05c0c0-cb11-4bea-b833-1085410512ac', '4abcb5f2-70c6-4d66-81b8-fd9c2b6f1e17', '3ba54906-9e1f-4366-9623-7c4d283d604e', '3fc54317-72f2-45a2-9f76-8651d65faa18', '648aba26-0712-4833-b1a8-5399e3db1cb0', 'e838f6a0-9219-40a1-b0cb-ebee815969fc'], merged_from_count=11),
  0.5),
 (KGEntity(id='872444ae-f365-4fbb-8e4c-6e03688c3c4d', graph_name='book3_ch0-7', name='Mauretania', entity_type='polity', aliases=[], descriptions=['A region that became a Roman province in AD 42.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:4'], source_pages=[345], source_paragraph_ids=['ca863ea0-5b1a-4c36-b999-a7a9da4244a9'], merged_from_count=1),
  0.5),
 (KGEntity(id='6a6bd752-aa6c-42d8-8e5c-6e43df3a7274', graph_name='book3_ch0-7', name='Commodus', entity_type='person', aliases=[], descriptions=['Son of Marcus Aurelius whose succession marked the end of the Antonine golden age.', 'The last Antonine emperor whose assassination in 192 led to a period of civil wars.'], occurrence_count=2, book_indices=[3], source_book_chapters=['3:4', '3:5'], source_pages=[344, 384], source_paragraph_ids=['343daff2-2a5f-48f5-b12e-83e4bfc54dd5', 'c83771b4-0d77-4c2d-9870-8c932332248c'], merged_from_count=2),
  0.5),
 (KGEntity(id='cee76ffe-00d4-4f02-b6e7-c218de7ce5bf', graph_name='book3_ch0-7', name='Persian Gulf', entity_type='place', aliases=[], descriptions=['Region reached by Trajan during his campaign against Parthia.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:4'], source_pages=[346], source_paragraph_ids=['1cfb6550-4c6e-4c63-a181-7dc7a3a15e46'], merged_from_count=1),
  0.4517925977706909),
 (KGEntity(id='dfc14c46-692a-4c69-97b9-475fd1d0b518', graph_name='book3_ch0-7', name='Parthian Empire', entity_type='polity', aliases=['Parthians', 'Parthia', 'Parthia (Parthian Empire)'], descriptions=['Empire established by Mithridates I, stretching from Bactria in the east to Babylonia in the west.', 'An Iranian nomadic people who created political unity in Iran and Mesopotamia and were known for mounted archery.', 'A kingdom in the east that emerged as a new threat and an important satrapy south-east of the Caspian Sea.', 'A polity located on the Euphrates, facing a new power from the west.', 'A major power with dynastic instability and contested control over Armenia.', 'A great power in Asia with a strong army including mounted archers and cataphracts.', 'Eastern polity against which Caesar planned a great campaign.', 'A polity that harassed Syria and encouraged unrest among Palestinian Jews, involved in civil war politics against Rome.', 'One of the groups that followed the Indo-Greeks of Bactria and established themselves in the Punjab.'], occurrence_count=9, book_indices=[3], source_book_chapters=['3:3', '3:4', '3:6'], source_pages=[312, 313, 340, 345, 346, 445], source_paragraph_ids=['bedf83eb-0968-46f4-9f55-64670a1b43f3', 'e0fc964b-973b-4e72-883b-703e86e1d251', '01f84f6a-0902-49f7-ab19-fa9343e44aed', '32a2a270-279d-471d-8250-a447ef875a2e', 'b9b8b555-088a-4da9-a46f-db3112ff31bc', '00e27974-33f2-4e98-aab0-e97511ccdb82', 'bb6ff2e0-0363-4123-a598-65eac2648512', '1cfb6550-4c6e-4c63-a181-7dc7a3a15e46', 'e531a0c6-ba46-4aad-8994-013584ffe079'], merged_from_count=9),
  0.40042102336883545),
 (KGEntity(id='54a5668d-cc39-4916-993b-60e635211e3b', graph_name='book3_ch0-7', name='Marcus Licinius Crassus', entity_type='person', aliases=['Crassus'], descriptions=['Roman politician who launched an invasion of Parthia in 54 BC and was killed.', 'Roman general from whom the Roman standards were taken.'], occurrence_count=2, book_indices=[3], source_book_chapters=['3:4'], source_pages=[345, 346], source_paragraph_ids=['1cfb6550-4c6e-4c63-a181-7dc7a3a15e46', 'bb6ff2e0-0363-4123-a598-65eac2648512'], merged_from_count=2),
  0.35283783078193665),
 (KGEntity(id='26a98201-1ad3-4f07-af9e-8539e701b893', graph_name='book3_ch0-7', name='Ardashir I', entity_type='person', aliases=['Artaxerxes'], descriptions=['A ruler from the Sassanid dynasty who took the Kushan capital of Peshawar.', 'King who killed the last king of Parthia and founded the Sassanid dynasty around 225.', 'A ruler who took Bactria and the Kabul valley early in the third century AD.'], occurrence_count=3, book_indices=[3], source_book_chapters=['3:5', '3:6'], source_pages=[389, 446], source_paragraph_ids=['4fe58a41-098d-4d03-bbe0-6867e560a190', '2d87f023-9d4e-4ccc-9ab3-30a2f432163f'], merged_from_count=3),
  0.264563649892807),
 (KGEntity(id='9f40590a-182f-4993-be3b-0cbf2104f654', graph_name='book3_ch0-7', name='Polybius', entity_type='person', aliases=[], descriptions=["Historian sent as a hostage to Rome who wrote a scientific history of Rome's conquests."], occurrence_count=1, book_indices=[3], source_book_chapters=['3:4'], source_pages=[332], source_paragraph_ids=['6417aa26-58f9-49bb-853e-dd05909e4806'], merged_from_count=1),
  0.22516217827796936)]

In [6]:
parthia_entity = search_res[6][0]
print(f"Entity: {parthia_entity.name} ({parthia_entity.entity_type})")

Entity: Parthian Empire (polity)

In [7]:
parthia_entity.__dict__

{'id': 'dfc14c46-692a-4c69-97b9-475fd1d0b518',
 'graph_name': 'book3_ch0-7',
 'name': 'Parthian Empire',
 'entity_type': 'polity',
 'aliases': ['Parthians', 'Parthia', 'Parthia (Parthian Empire)'],
 'descriptions': ['Empire established by Mithridates I, stretching from Bactria in the east to Babylonia in the west.',
  'An Iranian nomadic people who created political unity in Iran and Mesopotamia and were known for mounted archery.',
  'A kingdom in the east that emerged as a new threat and an important satrapy south-east of the Caspian Sea.',
  'A polity located on the Euphrates, facing a new power from the west.',
  'A major power with dynastic instability and contested control over Armenia.',
  'A great power in Asia with a strong army including mounted archers and cataphracts.',
  'Eastern polity against which Caesar planned a great campaign.',
  'A polity that harassed Syria and encouraged unrest among Palestinian Jews, involved in civil war politics against Rome.',
  'One of the groups that followed the Indo-Greeks of Bactria and established themselves in the Punjab.'],
 'occurrence_count': 9,
 'book_indices': [3],
 'source_book_chapters': ['3:3', '3:4', '3:6'],
 'source_pages': [312, 313, 340, 345, 346, 445],
 'source_paragraph_ids': ['bedf83eb-0968-46f4-9f55-64670a1b43f3',
  'e0fc964b-973b-4e72-883b-703e86e1d251',
  '01f84f6a-0902-49f7-ab19-fa9343e44aed',
  '32a2a270-279d-471d-8250-a447ef875a2e',
  'b9b8b555-088a-4da9-a46f-db3112ff31bc',
  '00e27974-33f2-4e98-aab0-e97511ccdb82',
  'bb6ff2e0-0363-4123-a598-65eac2648512',
  '1cfb6550-4c6e-4c63-a181-7dc7a3a15e46',
  'e531a0c6-ba46-4aad-8994-013584ffe079'],
 'merged_from_count': 9}

In [8]:
seed_id = parthia_entity.source_paragraph_ids[0]
print(f"\nSource paragraph ID: {seed_id}")

Source paragraph ID: bedf83eb-0968-46f4-9f55-64670a1b43f3

In [9]:

# Step 1: Find entities in the seed paragraph
seed_entities = mgr.kg_entities.find_by_paragraph(seed_id, graph_name)
print(f"Entities in paragraph {seed_id[:8]}...:")
for e in seed_entities:
    print(f"  {e.name} ({e.entity_type}) — aliases={e.aliases}, occurrences={e.occurrence_count}")

Entities in paragraph bedf83eb...:
  Parthian Empire (polity) — aliases=['Parthians', 'Parthia', 'Parthia (Parthian Empire)'], occurrences=9
  Roman Senate (polity) — aliases=['Senate'], occurrences=19
  Julius Caesar (person) — aliases=['Julius', 'Caesar'], occurrences=10

In [10]:
# Step 2: Find 1st-order hop relationships from seed entities
seed_entity_ids = [e.id for e in seed_entities]
rels = mgr.kg_relationships.find_by_entities(seed_entity_ids, graph_name)
print(f"Relationships involving seed entities: {len(rels)}")
for r in rels:
    print(f"  {r.source_entity_name} --[{r.relation_type}]--> {r.target_entity_name}  (temporal: {r.temporal_context or '-'})")

Relationships involving seed entities: 76
  Parthia --[conquered]--> Seleucid kingdom  (temporal: third century BC)
  Parthia --[influenced]--> Silk Road  (temporal: -)
  Parthians --[part_of]--> Iran  (temporal: -)
  Parthians --[part_of]--> Mesopotamia  (temporal: -)
  Parthians --[influenced]--> Seleucids  (temporal: -)
  Mithridates I --[ruled]--> Parthian empire  (temporal: second century BC)
  Mithridates II --[ruled]--> Parthian empire  (temporal: second century BC)
  Parthia --[opposed]--> Rome  (temporal: -)
  Roman Senate --[part_of]--> Rome  (temporal: -)
  Roman Senate --[opposed]--> Roman People  (temporal: -)
  Senate --[part_of]--> Roman Republic  (temporal: 300 BC)
  Senate --[ruled]--> Roman Republic  (temporal: 300 BC)
  Senate --[part_of]--> patricians  (temporal: 300 BC)
  Senate --[part_of]--> plebs  (temporal: 300 BC)
  consul --[part_of]--> Senate  (temporal: -)
  consuls --[ruled]--> Senate  (temporal: end of the sixth century BC)
  quaestors --[part_of]--> Senate  (temporal: -)
  plebs --[opposed]--> Senate  (temporal: -)
  Tribunes of the People --[allied_with]--> Senate  (temporal: earlier republic and often thereafter)
  Senate --[part_of]--> republic  (temporal: -)
  Senate --[ruled]--> Italy  (temporal: -)
  Senate --[ruled]--> special court  (temporal: 149 BC)
  Senate --[ruled]--> equites  (temporal: -)
  Senate --[ruled]--> generals  (temporal: -)
  Julius Caesar --[ruled]--> Gaul  (temporal: 59 BC to 52 BC)
  Julius Caesar --[allied_with]--> Pompey  (temporal: -)
  Julius Caesar --[ruled]--> Rome  (temporal: 59 BC)
  Marius’s wife --[part_of]--> Julius Caesar  (temporal: -)
  Caesar --[ruled]--> Gaul  (temporal: -)
  Caesar --[conquered]--> Gaul  (temporal: -)
  Caesar --[part_of]--> Roman Republic  (temporal: -)
  Caesar --[participated_in]--> Roman Republic  (temporal: January 49 BC)
  Caesar --[conquered]--> River Rubicon  (temporal: January 49 BC)
  Caesar --[conquered]--> Rome  (temporal: January 49 BC)
  Senate --[allied_with]--> Pompey  (temporal: -)
  Caesar --[opposed]--> Pompey  (temporal: -)
  Caesar --[part_of]--> Egypt  (temporal: -)
  Caesar --[allied_with]--> Cleopatra  (temporal: -)
  Caesar --[conquered]--> Spain  (temporal: 45 BC)
  Julius Caesar --[ruled]--> Rome  (temporal: -)
  Julius Caesar --[part_of]--> Rome  (temporal: -)
  Julius Caesar --[allied_with]--> Senate  (temporal: -)
  Julius Caesar --[opposed]--> money-lenders  (temporal: -)
  Julius Caesar --[influenced]--> Julian calendar  (temporal: 45 BC)
  Caesar --[participated_in]--> Senate  (temporal: 15 March 44 BC)
  Caesar --[opposed]--> Parthians  (temporal: -)
  Julius Caesar --[influenced]--> The republic  (temporal: -)
  Octavian --[succeeded]--> Julius Caesar  (temporal: -)
  Octavian --[succeeded]--> Julius Caesar  (temporal: -)
  Octavian --[allied_with]--> Senate  (temporal: 27 BC)
  Senate --[allied_with]--> Augustus  (temporal: -)
  Augustus --[succeeded]--> Julius Caesar  (temporal: AD 14)
  Julius Caesar --[ruled]--> Roman Empire  (temporal: -)
  Senate --[part_of]--> Roman Empire  (temporal: -)
  Senate --[opposed]--> Tiberius  (temporal: -)
  Julius Caesar --[part_of]--> Roman Empire  (temporal: -)
  Rome --[opposed]--> Parthia  (temporal: 92 BC)
  Pompey --[opposed]--> Parthia  (temporal: -)
  Crassus --[opposed]--> Parthia  (temporal: 54 BC)
  Parthians --[opposed]--> Rome  (temporal: -)
  Parthians --[opposed]--> Syria  (temporal: -)
  Parthians --[opposed]--> Palestinian Jews  (temporal: -)
  Augustus --[opposed]--> Parthia  (temporal: -)
  Trajan --[conquered]--> Parthia  (temporal: -)
  Hadrian --[allied_with]--> Parthia  (temporal: -)
  Senate --[ruled]--> Roman Empire  (temporal: -)
  Roman Senate --[ruled]--> Herod the Great  (temporal: 37 BC)
  Senate --[ruled]--> emperor  (temporal: -)
  Senate --[succeeded]--> army  (temporal: -)
  senatorial rank --[succeeded]--> Senate  (temporal: -)
  Senate --[part_of]--> Ravenna  (temporal: 402)
  Senate --[part_of]--> Western Roman Empire  (temporal: 402)
  Senate --[ruled]--> Rome  (temporal: -)
  Theodoric --[allied_with]--> Senate  (temporal: -)
  Senate --[allied_with]--> Emperor  (temporal: -)
  Parthians --[part_of]--> India  (temporal: -)

In [11]:
# Step 3: Collect all connected entities (1-hop neighbors)
neighbor_ids = set()
for r in rels:
    neighbor_ids.add(r.source_entity_id)
    neighbor_ids.add(r.target_entity_id)

# Fetch neighbor entities not already in seed set
new_ids = neighbor_ids - set(seed_entity_ids)
all_entities = {e.id: e for e in seed_entities}
for nid in new_ids:
    entity = mgr.kg_entities.get_by_id(nid)
    if entity:
        all_entities[nid] = entity

print(f"Seed entities: {len(seed_entities)}")
print(f"1-hop neighbors: {len(new_ids)}")
print(f"Total subgraph entities: {len(all_entities)}")

Seed entities: 3
1-hop neighbors: 44
Total subgraph entities: 47

In [12]:
# Step 4: Visualize subgraph with PyVis
from pyvis.network import Network

TYPE_COLORS = {
    "person": "#4e79a7",
    "polity": "#f28e2b",
    "place": "#e15759",
    "event": "#76b7b2",
    "concept": "#59a14f",
}

net = Network(height="600px", width="100%", notebook=True, cdn_resources="in_line")
net.barnes_hut(gravity=-3000, spring_length=150)

# Add nodes — seed entities are larger
for eid, e in all_entities.items():
    is_seed = eid in seed_entity_ids
    color = TYPE_COLORS.get(e.entity_type, "#999999")
    net.add_node(
        eid,
        label=e.name,
        title=f"{e.name}\nType: {e.entity_type}\nAliases: {', '.join(e.aliases) if e.aliases else '-'}\nOccurrences: {e.occurrence_count}",
        color=color,
        size=25 if is_seed else 15,
        borderWidth=3 if is_seed else 1,
    )

# Add edges
for r in rels:
    if r.source_entity_id in all_entities and r.target_entity_id in all_entities:
        net.add_edge(
            r.source_entity_id,
            r.target_entity_id,
            title=f"{r.relation_type}\n{r.temporal_context or ''}",
            label=r.relation_type,
            font={"size": 9},
        )

net.show("kg_subgraph.html")
print(f"Graph saved to kg_subgraph.html — {len(all_entities)} nodes, {len(rels)} edges")

kg_subgraph.html
Graph saved to kg_subgraph.html — 47 nodes, 76 edges

# Inspect largest entities

In [18]:
top_entities = mgr.kg_entities.find_by_criteria(criteria={"graph_name": graph_name}, sort_by="occurrence_count", ascending=False, limit=10)

In [20]:
for entity in top_entities:
    print(f"{entity.name} ({entity.entity_type}) — occurrences: {entity.occurrence_count}, aliases: {entity.aliases}")

Roman Empire (polity) — occurrences: 121, aliases: ['republic', 'Roman administration', 'Rome (Roman Republic)', 'Rome (Roman Republic / Roman Empire)', 'early republic', 'Rome', 'Roman society', 'eastern empire', 'Roman government', 'Romans', 'Rome (Roman Republic / early Roman state)', 'old empire', 'The republic', 'Romans (Roman Empire)', 'Empire in the west', 'Roman authorities', 'western empire', 'empire', 'Empire', 'Eastern Empire']
Greeks (polity) — occurrences: 45, aliases: ['Greek society', 'Greek thought', 'ancient Greece', 'Greek', 'Hellenistic kingdoms', 'Greek literature', 'Greek world', 'archaic Greece', 'city-states of Greece', 'classical Greece', 'Hellenes', 'these states', 'Greek cities']
Persia (polity) — occurrences: 40, aliases: ['Persians', 'Achaemenid Persians (Achaemenid Empire)', 'Persian power', 'Achaemenids']
Rome (place) — occurrences: 36, aliases: ['church of Rome']
Athens (polity) — occurrences: 29, aliases: ['Athenians']
Christianity (concept) — occurrences: 25, aliases: ['early Christianity', 'Christian Church', 'Christian']
Jews (polity) — occurrences: 23, aliases: ['Jewish communities', 'Kingdom of Judah', 'Jewish proselytes', 'Judah']
Han dynasty (polity) — occurrences: 21, aliases: ['restored Eastern Han dynasty', 'Han state', 'Han China', 'Han empire', 'Han times', 'Han', 'Han Empire']
Roman Senate (polity) — occurrences: 19, aliases: ['Senate']
Alexander the Great (person) — occurrences: 18, aliases: ['Alexander', 'the Great']

## Investigate: Persia relationships

In [25]:
ent_persia = top_entities[2]

In [27]:
rels_persia = mgr.kg_relationships.find_by_entities(entity_ids=[ent_persia.id], graph_name=graph_name)

In [28]:
for rel in rels_persia:
    print(f"{rel.source_entity_name} --[{rel.relation_type}]--> {rel.target_entity_name}  (temporal: {rel.temporal_context or '-'})")

Persians --[conquered]--> Egypt  (temporal: 525)
Persia --[opposed]--> Lydia  (temporal: -)
Persia --[conquered]--> Peloponnese  (temporal: -)
Darius --[ruled]--> Persia  (temporal: -)
Greece --[opposed]--> Persia  (temporal: -)
Persia --[conquered]--> Lydia  (temporal: about 540 BC)
Persia --[conquered]--> Ionia  (temporal: -)
Cyrus --[ruled]--> Persia  (temporal: -)
Greek cities in Asia --[opposed]--> Persia  (temporal: early fifth century BC)
Persians --[conquered]--> Eretria  (temporal: 490 BC)
Persians --[opposed]--> Greeks  (temporal: -)
Athenians --[opposed]--> Persians  (temporal: 490 BC)
Persians --[conquered]--> Mount Athos  (temporal: -)
Persians --[participated_in]--> Marathon  (temporal: 490 BC)
Sparta --[opposed]--> Persia  (temporal: -)
Athens --[opposed]--> Persia  (temporal: -)
Persian army --[part_of]--> Persians  (temporal: 480 BC)
Greek civilization --[opposed]--> Persians  (temporal: -)
Delian League --[opposed]--> Persia  (temporal: -)
Spartans --[allied_with]--> Persia  (temporal: -)
fifth century BC --[participated_in]--> Persians  (temporal: fifth century BC)
Greek cities of Asia --[opposed]--> Persia  (temporal: -)
Herodotus --[conquered]--> Persian empire  (temporal: -)
Macedon --[conquered]--> Persia  (temporal: second half of the fourth century BC)
Persian power --[allied_with]--> Sparta  (temporal: -)
Anabasis of Xenophon --[part_of]--> Persian power  (temporal: -)
Egypt --[conquered]--> Persian power  (temporal: 404 BC)
western satraps --[opposed]--> Persian power  (temporal: -)
Persian power --[ruled]--> Egypt  (temporal: -)
Alexander --[ruled]--> Persia  (temporal: -)
Alexander --[opposed]--> Persians  (temporal: -)
Alexander --[conquered]--> Persia  (temporal: 334 BC)
Alexander --[conquered]--> Persians  (temporal: -)
Darius III --[ruled]--> Persians  (temporal: -)
Alexander --[influenced]--> Persia  (temporal: -)
Alexander --[ruled]--> Persia  (temporal: fourth century BC)
Seleucids --[succeeded]--> Achaemenids  (temporal: -)
Persian empire --[influenced]--> Middle East  (temporal: -)
Persian empire --[influenced]--> Mediterranean economy  (temporal: -)
Alexander --[influenced]--> Persians  (temporal: -)
Achaemenid Persia --[succeeded]--> Sumer  (temporal: by about 500 BC)
Roman Empire --[ruled]--> Persians  (temporal: -)
Persian Empire --[conquered]--> Babylon  (temporal: 539 BC)
Judah --[ruled]--> Persian Empire  (temporal: fifth century BC)
Egypt --[opposed]--> Persian Empire  (temporal: fifth century BC)
Rome --[opposed]--> Parthia  (temporal: -)
Parthia --[influenced]--> Jewish unrest  (temporal: -)
Romans --[opposed]--> Parthians  (temporal: second century AD)
Ardashir --[conquered]--> Parthia  (temporal: about 225)
Sassanid empire --[influenced]--> Achaemenid empire  (temporal: -)
Persians --[conquered]--> Syria  (temporal: -)
Emperor Valerian --[opposed]--> Persians  (temporal: 260)
Shapur I --[ruled]--> Persians  (temporal: 260)
Roman empire --[opposed]--> Persia  (temporal: -)
client states --[part_of]--> Persia  (temporal: -)
Persia --[opposed]--> Roman Empire  (temporal: -)
eastern empire --[opposed]--> Persians  (temporal: by 500)
Persia --[opposed]--> Eastern Empire  (temporal: -)
Nestorians --[part_of]--> Persia  (temporal: -)
Jews --[part_of]--> Persia  (temporal: -)
Ashoka --[influenced]--> Persian civilization  (temporal: -)
China --[allied_with]--> Persia  (temporal: until the beginning of the seventh century AD)

# Investigate: two frances

In [30]:
graph_name = "book7_ch0-6"

## text search

In [33]:
mgr.kg_entities.search_entities_hybrid(query_text="France", graph_name=graph_name, limit=20)

[(KGEntity(id='0e922b0e-e4e6-43eb-a5e1-4786fa82cc7f', graph_name='book7_ch0-6', name='France', entity_type='polity', aliases=['Russian state', 'Russians', 'French', 'Russia', 'tsarist state', 'Great Britain', 'Allied governments'], descriptions=["A major polity comprising a quarter of Europe's population in 1900.", 'A country in Europe with slow economic and social progress, experiencing revolutionary movements in the early 20th century.', 'A European great power involved in a war with Turkey in 1876.', 'A great dynastic empire facing internal problems and political revolution in 1905.', 'A major polity undergoing economic advance and social challenges in the early twentieth century.', 'A colonial power that came into conflict with the United Kingdom in various global locations.', 'A nation defeated militarily by Japan.', 'A major European state with an older political constitution than the United States in 1914.', 'A great state involved in the European balance of power before 1914.', 'A major empire involved in rivalry with Austria-Hungary in south-eastern Europe.', "A major power offended by Austria-Hungary's annexation of Bosnia without compensating gains.", "A major power supporting Serbia and opposing Austria-Hungary's influence in the region.", 'A major state allied with Germany and Austria-Hungary under dynastic resistance to revolutionary dangers.', 'Became an ally of France in 1892.', 'A major European state improving its military and reliant on Black Sea ports for grain export.', 'A European power involved in imperial quarrels with Great Britain in Africa and Asia.', 'A major polity involved in spheres of interest in Persia.', 'Power supporting Serbia and rebuilding its forces in the early 20th century.', 'Mobilized to protect Serbia and was declared war on by Germany.', 'A European great power, socially conservative, intellectually vital but conscious of military weakness and slow industrialization.', 'A colonial power in conflict with the United Kingdom around the globe in 1900.', "A major European power targeted for isolation by Bismarck's policies.", 'A republic and major state, from which Germany seized Alsace and Lorraine in 1871.', 'An ally of Russia from 1892, targeted by German irritation in 1905 and 1911.', 'A major European state likely to join a war involving Austria and Russia.', 'A European power with imperial ambitions clashing with Great Britain in Africa and Asia.', "A European country involved in an agreement with Britain and subject to German pressure over Morocco's affairs.", 'Target of German attack and war declaration as part of German military planning.', 'The coalition including France, Great Britain, Russia, and others opposing the Central Powers in World War I.', 'A major belligerent in the war, losing territory and suffering heavy casualties.', 'The coalition opposing the Central Powers in World War I, including Britain and France.', 'A coalition accessible to the United States and Japan during the war.', 'A coalition that liquidated investments in the United States to pay for their needs and became debtors.', 'The coalition opposing Germany in World War I, whose propaganda and war aims influenced American opinion.', 'The coalition opposing the Central Powers in World War I.', 'A major power that collapsed during World War I, ceasing to be a great power by the end of 1917.', 'The state destroyed by the war leading to revolutionary transformation in central and eastern Europe.', 'The old imperialist regime in Russia that was succeeded by the USSR.', 'Refers to the French colonial power involved in suppressing a Vietnamese revolt in 1930.', 'Western power whose protests against Japanese actions were ineffective due to troubles elsewhere.', 'European power forced by Japan to admit an occupying army to Indochina.'], occurrence_count=41, book_indices=[7], source_book_chapters=['7:1', '7:2', '7:3'], source_pages=[1236, 1240, 1250, 1264, 1265, 1266, 1267, 1268, 1269, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1281, 1282, 1318, 1328, 1331, 1332], source_paragraph_ids=['36bb8c37-f068-402b-89d3-4443cc8bf3a2', 'b3e75e36-4d2c-4973-a3d6-ab93cc02a352', '3482339f-0add-47bb-9c46-1e846dfecd22', '4fce6ef4-ff7c-42ba-bc10-0088af9da44c', 'c2379b38-e1bf-4b3d-bcb4-3f867295cdbc', '994a1160-c07d-45ee-a43e-71665fde16b5', '307017ff-6542-406d-b316-12e02e7b449f', '08035707-4d15-4483-b1e9-6ffc383e4f74', '17acf246-9813-4238-949e-fdce65351075', '721ef602-e376-4398-ae2e-4e556a472a4c', 'dd31150d-a6fb-49db-934e-f6a7a43003f2', '9477ab21-6dc2-4f62-a72c-08b690c46c9b', '994ffcc4-02a4-4350-a00c-50a9715b7997', '00e17d64-3614-4eef-acab-4dff92758616', '59f27b88-0344-4d1e-a3d4-8b837c91fe50', '54f03528-49ac-4dc4-93e5-35a8bba38eed', 'fc5233b6-ebc2-466d-8d19-a5ffe9e500a3', '1c78b01a-2ae6-4154-ab46-a7f198a98dc2', '861b2bb8-1e59-49c8-a41e-beff972f43b7', 'fcfbec84-1079-4145-84b8-f3bfb92a6053', 'c618f979-34a8-406d-80c5-5fc3136c250a', '98146fc9-46f1-4112-bbc9-99e2662b0805', '4ef76f06-34d0-4cd5-84b5-1e3d6fd24833', '405f3232-d881-4e02-8938-c6a8a2fc01cc', '1adff864-ef97-4fa9-9f0b-547ce507f14b', 'c3611acf-b151-4563-854b-ee6424703df6', 'd9dd8063-2970-4fcc-9e08-dcad551a5593', '145e2058-78ac-4ab1-bc30-ff42187b3c75', '4537c586-62fe-4708-beb8-ce4ef3f12ea6', '0b31f635-e895-42ce-8694-b82e14a68fef', 'fc12ddca-de33-42fb-a6be-f2b55731aac9', 'e9f8e099-7ebc-49d2-80a7-07d1b1852581', 'd00bb008-f60c-4cd8-b23d-d7dd722bc3b1', '3d03513f-28c0-43d3-895c-9b68fdb8a773'], merged_from_count=41),
  0.5),
 (KGEntity(id='2e0ed9d2-69f9-4d05-87c1-91c08d39b42a', graph_name='book7_ch0-6', name='First president of Israel', entity_type='person', aliases=[], descriptions=["Leader who reportedly encouraged Israel's nuclear energy program after 1948."], occurrence_count=1, book_indices=[7], source_book_chapters=['7:6'], source_pages=[1418], source_paragraph_ids=['33cbcbb9-1fec-4e13-857a-712bd96cfb59'], merged_from_count=1),
  0.5),
 (KGEntity(id='6495cb59-4999-4ed9-8028-6f7415e473d0', graph_name='book7_ch0-6', name='Alsace', entity_type='place', aliases=[], descriptions=['A province transferred from France to Germany in 1871.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:1'], source_pages=[1249], source_paragraph_ids=['4ba5711e-6106-4f83-8665-5abcbfa1c4cb'], merged_from_count=1),
  0.45307427644729614),
 (KGEntity(id='594f1ac0-b528-4b40-b462-69b2f6ff5897', graph_name='book7_ch0-6', name='Lorraine', entity_type='place', aliases=[], descriptions=['A province transferred from France to Germany in 1871.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:1'], source_pages=[1249], source_paragraph_ids=['4ba5711e-6106-4f83-8665-5abcbfa1c4cb'], merged_from_count=1),
  0.45307427644729614),
 (KGEntity(id='66282939-5f03-4123-913c-397d9a55e093', graph_name='book7_ch0-6', name='Anglo-French settlement', entity_type='event', aliases=[], descriptions=['A settlement between Britain and France that evolved into an entente.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:2'], source_pages=[1275], source_paragraph_ids=['fc12ddca-de33-42fb-a6be-f2b55731aac9'], merged_from_count=1),
  0.4363211691379547),
 (KGEntity(id='ffb0913f-4967-4f98-aaa2-cb647d49d14f', graph_name='book7_ch0-6', name='Algeria', entity_type='place', aliases=[], descriptions=['Territory governed as a département of metropolitan France, not technically a colony.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:6'], source_pages=[1398], source_paragraph_ids=['bfae3382-1b6b-4a8d-a906-1badc505267c'], merged_from_count=1),
  0.4283667504787445),
 (KGEntity(id='e9fb4906-8cbc-42d5-ab06-052136bd61a6', graph_name='book7_ch0-6', name='Communist Party', entity_type='concept', aliases=[], descriptions=['Political parties in Italy and France committed to revolutionary overthrow of capitalism.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:5'], source_pages=[1382], source_paragraph_ids=['5eef4fa7-b204-4910-a677-c8747e3d3b88'], merged_from_count=1),
  0.4283667504787445),
 (KGEntity(id='6e5fdf73-4b09-4ceb-9299-5a232824317c', graph_name='book7_ch0-6', name='Anglo-French proposals for spheres of influence in the Middle East', entity_type='concept', aliases=[], descriptions=['Secret agreements dividing influence in the Middle East between Britain and France.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:4'], source_pages=[1344], source_paragraph_ids=['d2dea678-6f39-449e-a794-6fe758cb7d64'], merged_from_count=1),
  0.4283667504787445),
 (KGEntity(id='f3a35fa1-a073-4baa-a81d-5974e509edeb', graph_name='book7_ch0-6', name='Levant', entity_type='place', aliases=[], descriptions=['Region in the Middle East where France claimed special cultural and religious influence.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:4'], source_pages=[1343], source_paragraph_ids=['0261abd1-f37e-4c49-9036-ad6853bb6b84'], merged_from_count=1),
  0.4206751585006714),
 (KGEntity(id='beade483-6c61-4aaa-92c7-0f9d712dd755', graph_name='book7_ch0-6', name='French army', entity_type='polity', aliases=[], descriptions=['The military force of France during World War I, which experienced mutinies in 1917.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:2'], source_pages=[1282], source_paragraph_ids=['08035707-4d15-4483-b1e9-6ffc383e4f74'], merged_from_count=1),
  0.41323354840278625),
 (KGEntity(id='167edfb8-8882-46e2-abca-fd200f29848e', graph_name='book7_ch0-6', name='Passchendaele', entity_type='event', aliases=['Third Battle of Ypres'], descriptions=['A series of battles in France during World War I causing heavy British casualties.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:2'], source_pages=[1282], source_paragraph_ids=['08035707-4d15-4483-b1e9-6ffc383e4f74'], merged_from_count=1),
  0.41323354840278625),
 (KGEntity(id='bf00e206-8ea0-42a4-b8c6-c55fd698aeb7', graph_name='book7_ch0-6', name='Alsace and Lorraine', entity_type='place', aliases=[], descriptions=['Territories seized by Germany from France in 1871.', 'Territories lost by Germany as part of the settlement.'], occurrence_count=2, book_indices=[7], source_book_chapters=['7:2'], source_pages=[1273, 1289], source_paragraph_ids=['b89309d9-07dc-4468-87c1-474cb7ec92b6', '994ffcc4-02a4-4350-a00c-50a9715b7997'], merged_from_count=2),
  0.39229249954223633),
 (KGEntity(id='bcbc124f-b1ee-48e3-adff-4a29a326b3de', graph_name='book7_ch0-6', name='France', entity_type='polity', aliases=[], descriptions=['A permanent member of the United Nations Security Council, included at the insistence of Churchill.', 'A slowly reviving power unable to stand up to the Soviet army after the war.'], occurrence_count=2, book_indices=[7], source_book_chapters=['7:6'], source_pages=[1385, 1388], source_paragraph_ids=['470f9117-e809-45cb-9a8c-e56a96e2135f', '7885131f-07f2-40dd-a8af-14ed5270fc73'], merged_from_count=2),
  0.37656259536743164),
 (KGEntity(id='6a0cb407-62f8-4a74-8641-ed813cee86a6', graph_name='book7_ch0-6', name='France', entity_type='place', aliases=[], descriptions=['Country invaded by Anglo-American forces in June 1944.', 'Country expected to be attacked by German army', "Country where more perished in the 'purification' of liberation than in the great Terror of 1793."], occurrence_count=3, book_indices=[7], source_book_chapters=['7:2', '7:5', '7:6'], source_pages=[1284, 1378, 1392], source_paragraph_ids=['0e75d0b0-5eb7-4f19-bc9f-7e80a88d0380', 'eaa4fe34-8058-469c-adcf-fed3c4c73dfe', '3af3776d-8559-4df6-a2da-46a274d3508d'], merged_from_count=3),
  0.37656259536743164),
 (KGEntity(id='4286e4e7-a53e-4856-a3ff-016337a38c29', graph_name='book7_ch0-6', name='France', entity_type='polity', aliases=['French', 'French Empire', 'French empire'], descriptions=['One of the powers with which China had unequal treaties that were swept away during the Second World War.', 'French armed forces later admitted to Berlin administration after Soviet agreement.', 'Colonial power contrasted with British in terms of concessions to nationalist sentiment.', 'Colonial power in South-East Asia with colonies affected by World War II.', 'Colonial power in Indochina attempting to maintain control after WWII.', 'Colonial power trying to retain a diminished Vietnam and other Indochinese states within the French Union.', 'A great power that held League of Nations mandates in Syria and Lebanon until 1939.', 'Tried to re-establish authority in Syria and Lebanon after the war and faced nationalist movements in Algeria.', 'French colonial possessions where De Gaulle hoped to find sympathizers to continue the fight.', "A European country whose language and cultural influence spread in Egypt during Muhammad Ali's reforms.", 'Country where Ismail was educated and whose people and ideas he favored.', 'Had a special role and interests in the Levant and Middle East, including protection of Catholicism in the Ottoman Empire.', 'A major Allied power with special interests in Syria, involved in agreements on Ottoman empire partition.', 'One of the great powers engaged in the Middle East, awarded mandate for Syria and governed it forcefully.', 'A colonial power whose brutality in Syria caused Arab resentment.', 'One of the Allied powers that agreed on shares of the Ottoman territory and established spheres of influence.', 'One of the powers driven out by Mustafa Kemal.', 'A major western European power reconstituted after occupation and defeat, with a strengthened Communist Party.', 'A country overshadowed by a united Germany in central Europe.', 'A European country seeking allies against a German revival in eastern and central Europe.', 'A western European great power, militarily weak, invested in strategic defense by fortification against Germany.', "A great power and African colonial power involved in the League of Nations' response to Italy's invasion of Ethiopia.", 'Country with a large and active Communist Party, but where Communist aims were not accepted by the majority after the Depression.', 'Western power that might have encouraged a German attack on the USSR and declared war on Germany after the invasion of Poland.', 'One of the two constitutional great powers of Europe responding to German expansion.', 'Country invaded and defeated by Germany, signing an armistice on 22 June.', 'Country with a faction in exile during the war.', 'The country whose interests and honour he was custodian of.', 'A great power involved in nationalist disputes over Alsace and Lorraine.', 'A nation where anti-clericalism and priest-baiting were significant political issues in the late 19th century.', 'Victorious power concerned about German aggression, central to European security issues.', 'A major belligerent suffering heavy casualties.', 'A major Allied power during World War I.', 'The French state seeking to impose harsh terms on Germany to prevent future wars and ensure security.', 'A major country whose currency remained on the gold standard by 1933.'], occurrence_count=35, book_indices=[7], source_book_chapters=['7:1', '7:2', '7:4', '7:5', '7:6'], source_pages=[1249, 1252, 1281, 1282, 1286, 1289, 1307, 1334, 1336, 1343, 1344, 1345, 1348, 1349, 1357, 1358, 1361, 1363, 1368, 1369, 1370, 1371, 1372, 1382, 1393, 1399, 1406, 1410, 1411, 1412, 1413], source_paragraph_ids=['67b42ac4-1919-4dce-aaf4-0cefc1bf1a4c', 'a8e99da6-2e8c-455d-8071-838f73e269a8', '2f33dcff-5a1f-47f0-a180-6027e3c17d73', 'b89309d9-07dc-4468-87c1-474cb7ec92b6', '5b663eb2-13bc-4e88-81e8-a8206e8159f6', 'c6dd44ea-a64d-4fb4-97ba-9a36a9848a9e', 'e9ff1e16-65d8-413a-8a86-4ea4543252a6', '9c5cccf3-5710-4c1f-8bbc-fc78b299e317', '62934249-9d8e-4fb6-89da-335716925c88', '08035707-4d15-4483-b1e9-6ffc383e4f74', 'f2803256-51f5-41a0-b45f-b09d7bf8bf6e', 'c3a3774d-ed71-4f5a-8649-2391857a11d1', '0e8077b1-4f48-402f-a977-495c7488ad2e', '58fc0cb3-f0d9-4572-b167-b527d7f88f14', '6531b863-63f6-45b2-9184-7b4c296090d0', '3ead5a87-a737-44ba-99c1-03a10cb4fc3f', '94901470-f05b-4c79-911c-aa07594cdf53', '5eef4fa7-b204-4910-a677-c8747e3d3b88', '268edb86-1b62-425d-bc72-d2ca7b351382', 'c31bfaaa-a5fc-4ab8-8277-c17f16165045', '4bec8ea5-7a46-4327-9f8c-8f176743ae43', '0a5d4c51-4361-4419-9078-5b4d44b82593', '4d65bdee-ec03-4e5d-a5fc-a19a0c63b7a8', '4ba5711e-6106-4f83-8665-5abcbfa1c4cb', '5488505c-7105-4a44-8e59-63554ef4b4a0', '7438b1b8-15de-498c-90de-dbe6856ddc13', '0261abd1-f37e-4c49-9036-ad6853bb6b84', 'c2228e83-c5ed-494b-86e3-b8f0fc52bd02', 'b8211064-0999-4fe4-ae3b-9bdbc4fdd350', '0d760c7a-706e-4166-9562-013b872cb4b1', 'c8237fcd-3ff3-409a-a169-70663ed83c63', '4607e45b-f317-43b9-84a8-d7c317d5c62a', '25edb149-1b00-4804-b641-241c2f9297b5', 'dd370dd6-15a5-4978-a191-b83081089a7a', '35db43d1-653f-41c2-a51c-3629e89f0ccd'], merged_from_count=35),
  0.37656259536743164),
 (KGEntity(id='d74a61b2-b74a-44cb-91cf-02ac14dd2c70', graph_name='book7_ch0-6', name='Algeria', entity_type='polity', aliases=[], descriptions=['Colony characterized by bitter warfare between colonial state and indigenous peasantry.', 'Site of fighting in 1945 with nationalists seeking autonomy in federation with France.'], occurrence_count=2, book_indices=[7], source_book_chapters=['7:6'], source_pages=[1399, 1413], source_paragraph_ids=['c3a3774d-ed71-4f5a-8649-2391857a11d1', 'c6dd44ea-a64d-4fb4-97ba-9a36a9848a9e'], merged_from_count=2),
  0.35026082396507263),
 (KGEntity(id='9c0e0f35-debb-46c2-a86f-9332ef2814d4', graph_name='book7_ch0-6', name='metropolitan France', entity_type='polity', aliases=[], descriptions=['Governing polity of Algeria as a département.'], occurrence_count=1, book_indices=[7], source_book_chapters=['7:6'], source_pages=[1398], source_paragraph_ids=['bfae3382-1b6b-4a8d-a906-1badc505267c'], merged_from_count=1),
  0.2834387421607971),
 (KGEntity(id='e47acb1f-f8b9-44e1-9387-bfb353d8f982', graph_name='book7_ch0-6', name='Otto von Bismarck', entity_type='person', aliases=['Bismarck'], descriptions=["The quintessential conservative statesman who promoted Germany's colonial interests influenced by public opinion.", 'Leader who worked to isolate France and ensure German supremacy in the 1870s and 1880s.', 'German leader who orchestrated alliances among Germany, Russia, Austria-Hungary, and Italy.', 'A major historical figure whose successors allowed the Reinsurance treaty to lapse.'], occurrence_count=4, book_indices=[7], source_book_chapters=['7:1', '7:2'], source_pages=[1247, 1272, 1273], source_paragraph_ids=['54f03528-49ac-4dc4-93e5-35a8bba38eed', '994ffcc4-02a4-4350-a00c-50a9715b7997', 'f853c2cc-e252-4ed2-b0fc-92a999b68da6', '4537c586-62fe-4708-beb8-ce4ef3f12ea6'], merged_from_count=4),
  0.2384844720363617),
 (KGEntity(id='3e4821d5-cb3f-44af-af6f-a741ab26b6bd', graph_name='book7_ch0-6', name='Winston Churchill', entity_type='person', aliases=['Churchill'], descriptions=['Prime minister who led Britain during the crisis after the Norwegian campaign collapse.', 'British leader who gave a famous speech praising the Royal Air Force after the Battle of Britain.', 'British leader who warned of the consequences if the Nazi regime was not defeated.', "British political leader who highlighted the division of Europe by an 'Iron Curtain' in 1946.", "British leader who insisted on France's inclusion as a permanent member of the Security Council."], occurrence_count=5, book_indices=[7], source_book_chapters=['7:5', '7:6'], source_pages=[1372, 1379, 1385, 1395], source_paragraph_ids=['554f1865-7f7f-4100-b944-f0a07ddf0525', 'fae4adc3-badb-42c6-aab6-806efe6a53bc', '3a00b58c-fab8-40b3-81b2-1221adf6be83', '7885131f-07f2-40dd-a8af-14ed5270fc73', 'f2614f51-1287-43ca-a274-261f85a06b4f'], merged_from_count=5),
  0.18898190557956696),

## inspect in top entities

In [34]:
top_entities = mgr.kg_entities.find_by_criteria(criteria={"graph_name": graph_name}, sort_by="occurrence_count", ascending=False, limit=10)

In [35]:
top_entities

[KGEntity(id='5ddc709f-2dc1-43ea-828b-55556b30ca05', graph_name='book7_ch0-6', name='Germany', entity_type='polity', aliases=['German republic', 'German army', 'German Reich', 'Bismarck’s creation', 'German forces', 'Central Powers', 'democratic German republic', 'new Germany', 'Germans', 'German', 'Austria-Hungary', 'united Germany'], descriptions=['One of the most stricken countries in Europe with about 7½ million dwellings destroyed.', 'An industrial European country whose economic capacity was suppressed by the Allies and was divided after 1918.', 'A state whose colonial interests were promoted by Bismarck in response to public opinion.', 'A great power that acquired Alsace and Lorraine in 1871 and whose nationalism under Wilhelm II caused alarm in Europe.', 'A nation where anti-clericalism and priest-baiting were significant political issues in the late 19th century.', 'Republic in Germany dominated by socialists after defeat.', 'A new state formed less than forty years before 1900, with huge industrial and economic success and a conservative constitution influenced by a semi-feudal aristocracy.', 'A major industrial power producing more steel than Russia in 1910.', "The military force of Germany, superior to France's army as demonstrated in 1870.", 'A major industrial rival to the United Kingdom by 1900, superior in technology and method.', 'A major industrial nation whose pig-iron and steel production was surpassed by the United States by 1914.', 'A central power whose control was the issue in two major wars affecting Europe.', 'A great state involved in the European balance of power before 1914.', 'A major European power whose supremacy was sought by Bismarck through alliances.', 'A major state involved in alliances and conflicts in late 19th century Europe.', 'Central European power whose policy led to a divided Europe and prepared for a two-front war.', 'A major European state likely to join a war involving Austria and Russia.', 'A European power whose policy antagonized Great Britain at the end of the nineteenth century.', 'A European country that challenged Anglo-French agreements and sought influence in Morocco, leading to increased tensions with Britain and France.', 'Ally of Austria-Hungary, unlikely to avoid fighting Russia.', 'Supported Austria-Hungary and planned military actions including attacks on France and Russia.', 'The coalition including Germany, Austria-Hungary, Ottoman empire, and others opposing the Allies in World War I.', 'A major belligerent in the war, conducting offensives in northern France and the east.', 'The German military forces involved in the battles of Verdun and the Somme.', 'A coalition not accessible to the United States and Japan due to British naval supremacy.', 'Opposing force fought by the British white Dominions in their colonies.', 'A major polity engaged in warfare, conducting bombing raids on London by airship and subject to a British blockade.', 'A major belligerent in the war, facing blockade and fighting on two fronts.', 'A central power in World War I that conducted submarine warfare and sought alliances against the United States.', 'The opposing party in negotiations with Russia leading to the Treaty of Brest-Litovsk.', 'Military force expected to attack France in spring 1918', 'Central European state that patronized the Polish army and was involved in World War I.', 'An exhausted economic dynamo of central Europe at the center of post-war chaos.', 'Defeated power in World War I, presented with peace terms after negotiations.', 'A defeated enemy with whom peace had to be made after World War I.', 'The German state penalized by territorial losses and economic reparations after the war.', 'Country defeated in World War I', 'A new state adopting liberal, parliamentary, and often republican constitutions after the war.', 'A country where fierce nationalist resentments were created after the peace settlements.', 'A country where a movement similar to Fascism succeeded in a revolution overcoming historical conservatism.', 'One of the two major states where the new radical politics triumphed after 1918, with success coming in 1933.', 'The most important of all the European industrial states, burdened by reparations after the Versailles Treaty.', 'A European power with ports in China seized by Japan during World War I.', 'A major power at war with China in 1917.', 'A state regarded positively by Sun Yat-sen after 1921 for equal relations with China.', 'A major European power allied with the Ottoman Empire during World War I.', 'Country where a regime came to power in 1933 that persecuted Jews.', 'The centre of the old European power structure, partitioned into occupation zones after WWII.', 'A democratic German republic hoped to reconstruct German society and civilization.', 'A united country in central Europe, significant for its geography, population, and industrial power, central to the German problem in the 1930s.', 'A country involved in the post-World War I settlement and reparations.', 'A central European country whose containment was an international problem in the 1930s.', 'A European power that might revive and be confronted by western European powers.', 'A country where a radical and opportunist regime emerged, marking a major turning point.', 'Country where the Communist Party had significant votes before 1933 but did not displace the Social Democrats.', 'Country ruled by Adolf Hitler from 1933, redirected upon a course of aggression.', 'Country facing troubles attributed to various sources including the Treaty of Versailles and internal groups.', 'A European country that rearmed and expanded territorially in violation of the Treaty of Versailles.', "A polity pursuing territorial expansion in 1938-1939 under Hitler's leadership.", 'A major player in the Munich Agreement and the homeland of the transferred Germans.', 'Authoritarian state that attacked Poland, initiating the Second World War.', 'One of the forces that divided Poland and presented a danger to Europe through expansion.', 'The country that attempted a seaborne invasion and air bombardment of Great Britain and planned an invasion of the Soviet Union.', 'A state that decided to attack the USSR partly due to disagreements over Soviet expansion and strategic concerns.', 'The German military forces that overran Yugoslavia and Greece and took Crete in a spring campaign.', 'A major state launching an attack on 22 June 1941, initially successful but later pinned down by the Red Army counter-attacks.', 'A state allied with Japan and Italy with limited practical impact.', 'A country conducting military operations in the Balkans and supporting nationalist government in Iraq during World War II.', 'German military forces opposing Allies in North Africa and Russia', 'Axis power fighting on three fronts during World War II.', 'The German state or people who sought to implement the Final Solution.', 'A European country described as progressive but later associated with Nazism.', 'German military force encircled at Stalingrad', 'The German state created under Bismarck, partitioned after WWII.'], occurrence_count=74, book_indices=[7], source_book_chapters=['7:1', '7:2', '7:3', '7:4', '7:5', '7:6'], source_pages=[1247, 1249, 1252, 1263, 1264, 1265, 1266, 1267, 1269, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1283, 1284, 1285, 1286, 1289, 1292, 1295, 1296, 1303, 1305, 1314, 1315, 1320, 1344, 1347, 1357, 1358, 1361, 1362, 1363, 1364, 1367, 1368, 1369, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1382, 1392], source_paragraph_ids=['67b42ac4-1919-4dce-aaf4-0cefc1bf1a4c', '34e7e981-faf8-4708-98d5-8c2a55d49595', 'aee24c28-77ec-4978-bdf9-f82315d062da', '0e75d0b0-5eb7-4f19-bc9f-7e80a88d0380', 'b3e75e36-4d2c-4973-a3d6-ab93cc02a352', '3bae038d-398b-4347-8cb7-1dcea4295e3f', 'b89309d9-07dc-4468-87c1-474cb7ec92b6', 'ac938a3c-ebad-4ed7-8f39-8f5074a37405', '5b663eb2-13bc-4e88-81e8-a8206e8159f6', '4ca33910-dcb0-4653-a4e2-3327db14f0cb', 'a3375aba-b83c-41ca-8470-03479b997d9a', 'eaa4fe34-8058-469c-adcf-fed3c4c73dfe', '62934249-9d8e-4fb6-89da-335716925c88', '307017ff-6542-406d-b316-12e02e7b449f', 'c68ae882-4220-4595-b458-022d136ab766', '3a00b58c-fab8-40b3-81b2-1221adf6be83', '4a7a1676-e952-4f16-9688-537507828440', '721ef602-e376-4398-ae2e-4e556a472a4c', 'c75025ec-4494-47d8-bda0-76a69b6640c6', 'dd31150d-a6fb-49db-934e-f6a7a43003f2', '9477ab21-6dc2-4f62-a72c-08b690c46c9b', 'aa648f42-3ca9-4e15-bc83-17f61df9c323', '994ffcc4-02a4-4350-a00c-50a9715b7997', '4fa93501-1cfd-43f7-baa0-1b77071217f4', '0e923d7c-6bbf-4e5a-8c85-bb87a35d1755', '00e17d64-3614-4eef-acab-4dff92758616', 'e03311c7-032a-4efa-9d05-d119c91ebb8a', 'be41c2a1-0997-4c40-8584-7c2839d3d6eb', 'aa4c70a4-a46a-454a-be10-46273d8d6b12', 'b79d6751-c2ba-4fe9-9bd4-025c2c141998', '833907a6-c9ff-42ba-94ce-c45dab27d68a', '54f03528-49ac-4dc4-93e5-35a8bba38eed', 'd3a1bc4d-702e-4b23-ad63-bf8d9ec6755f', 'f4f54572-e8ca-48a9-8edf-f177b791e668', '1c78b01a-2ae6-4154-ab46-a7f198a98dc2', '56d6d327-1130-422f-95c4-bb2758a5baa5', '861b2bb8-1e59-49c8-a41e-beff972f43b7', '6531b863-63f6-45b2-9184-7b4c296090d0', '590d3ccf-c6e9-415e-be19-224dfd34bdb9', '5eef4fa7-b204-4910-a677-c8747e3d3b88', '82d2f25c-0ad4-410c-93ee-630c27a99ab2', '4d88184d-773d-407f-bd7a-6e793c7c8e51', '405f3232-d881-4e02-8938-c6a8a2fc01cc', '1adff864-ef97-4fa9-9f0b-547ce507f14b', '8bced7d4-62ad-4e7c-be98-f8b59201be97', '09a70467-3d05-42f0-8029-b90610cc2d9f', '268edb86-1b62-425d-bc72-d2ca7b351382', 'c31bfaaa-a5fc-4ab8-8277-c17f16165045', 'c3611acf-b151-4563-854b-ee6424703df6', '3af3776d-8559-4df6-a2da-46a274d3508d', '36fa8b83-6563-4197-b2c2-1b0df2f44d77', '4ba5711e-6106-4f83-8665-5abcbfa1c4cb', '187c6a80-269c-496b-ac8e-78917dc5f6cf', '2d17ba5c-c37d-486d-a0c8-230f68351e83', 'a0378b7c-9f62-4edc-a7e3-eb8e55a30817', 'f9fe6387-c691-4fda-9f30-44e6056b1a2b', '0d760c7a-706e-4166-9562-013b872cb4b1', 'c2228e83-c5ed-494b-86e3-b8f0fc52bd02', 'f853c2cc-e252-4ed2-b0fc-92a999b68da6', '145e2058-78ac-4ab1-bc30-ff42187b3c75', '4537c586-62fe-4708-beb8-ce4ef3f12ea6', 'e214a546-415b-49b7-9140-522b916df19c', '574afd1a-e8fa-45c7-8719-3c5ce6debab7', '020d8a1b-8534-4eda-a726-c8f30930b68d', 'c8237fcd-3ff3-409a-a169-70663ed83c63', '92ccf42b-0445-45c2-bd18-6952ff19eb13', 'ce65f765-79b3-4b9d-96c6-c08bf77a2788', '35db43d1-653f-41c2-a51c-3629e89f0ccd', 'e9f8e099-7ebc-49d2-80a7-07d1b1852581', '3d03513f-28c0-43d3-895c-9b68fdb8a773', 'daa4a36c-e1a8-45fc-a014-af44644af0bf', '0b71e3b4-9faa-46ab-9b44-1877eb712332'], merged_from_count=74),

### First occurance

In [45]:
ent_france_1 = top_entities[5]

In [46]:
ent_france_1.__dict__

{'id': '0e922b0e-e4e6-43eb-a5e1-4786fa82cc7f',
 'graph_name': 'book7_ch0-6',
 'name': 'France',
 'entity_type': 'polity',
 'aliases': ['Russian state',
  'Russians',
  'French',
  'Russia',
  'tsarist state',
  'Great Britain',
  'Allied governments'],
 'descriptions': ["A major polity comprising a quarter of Europe's population in 1900.",
  'A country in Europe with slow economic and social progress, experiencing revolutionary movements in the early 20th century.',
  'A European great power involved in a war with Turkey in 1876.',
  'A great dynastic empire facing internal problems and political revolution in 1905.',
  'A major polity undergoing economic advance and social challenges in the early twentieth century.',
  'A colonial power that came into conflict with the United Kingdom in various global locations.',
  'A nation defeated militarily by Japan.',
  'A major European state with an older political constitution than the United States in 1914.',
  'A great state involved in the European balance of power before 1914.',
  'A major empire involved in rivalry with Austria-Hungary in south-eastern Europe.',
  "A major power offended by Austria-Hungary's annexation of Bosnia without compensating gains.",
  "A major power supporting Serbia and opposing Austria-Hungary's influence in the region.",
  'A major state allied with Germany and Austria-Hungary under dynastic resistance to revolutionary dangers.',
  'Became an ally of France in 1892.',
  'A major European state improving its military and reliant on Black Sea ports for grain export.',
  'A European power involved in imperial quarrels with Great Britain in Africa and Asia.',
  'A major polity involved in spheres of interest in Persia.',
  'Power supporting Serbia and rebuilding its forces in the early 20th century.',
  'Mobilized to protect Serbia and was declared war on by Germany.',
  'A European great power, socially conservative, intellectually vital but conscious of military weakness and slow industrialization.',
  'A colonial power in conflict with the United Kingdom around the globe in 1900.',
  "A major European power targeted for isolation by Bismarck's policies.",
  'A republic and major state, from which Germany seized Alsace and Lorraine in 1871.',
  'An ally of Russia from 1892, targeted by German irritation in 1905 and 1911.',
  'A major European state likely to join a war involving Austria and Russia.',
  'A European power with imperial ambitions clashing with Great Britain in Africa and Asia.',
  "A European country involved in an agreement with Britain and subject to German pressure over Morocco's affairs.",
  'Target of German attack and war declaration as part of German military planning.',
  'The coalition including France, Great Britain, Russia, and others opposing the Central Powers in World War I.',
  'A major belligerent in the war, losing territory and suffering heavy casualties.',
  'The coalition opposing the Central Powers in World War I, including Britain and France.',
  'A coalition accessible to the United States and Japan during the war.',
  'A coalition that liquidated investments in the United States to pay for their needs and became debtors.',
  'The coalition opposing Germany in World War I, whose propaganda and war aims influenced American opinion.',
  'The coalition opposing the Central Powers in World War I.',
  'A major power that collapsed during World War I, ceasing to be a great power by the end of 1917.',
  'The state destroyed by the war leading to revolutionary transformation in central and eastern Europe.',
  'The old imperialist regime in Russia that was succeeded by the USSR.',
  'Refers to the French colonial power involved in suppressing a Vietnamese revolt in 1930.',
  'Western power whose protests against Japanese actions were ineffective due to troubles elsewhere.',
  'European power forced by Japan to admit an occupying army to Indochina.'],
 'occurrence_count': 41,
 'book_indices': [7],
 'source_book_chapters': ['7:1', '7:2', '7:3'],
 'source_pages': [1236,
  1240,
  1250,
  1264,
  1265,
  1266,
  1267,
  1268,
  1269,
  1271,
  1272,
  1273,
  1274,
  1275,
  1276,
  1277,
  1278,
  1279,
  1281,
  1282,
  1318,
  1328,
  1331,
  1332],
 'source_paragraph_ids': ['36bb8c37-f068-402b-89d3-4443cc8bf3a2',
  'b3e75e36-4d2c-4973-a3d6-ab93cc02a352',
  '3482339f-0add-47bb-9c46-1e846dfecd22',
  '4fce6ef4-ff7c-42ba-bc10-0088af9da44c',
  'c2379b38-e1bf-4b3d-bcb4-3f867295cdbc',
  '994a1160-c07d-45ee-a43e-71665fde16b5',
  '307017ff-6542-406d-b316-12e02e7b449f',
  '08035707-4d15-4483-b1e9-6ffc383e4f74',
  '17acf246-9813-4238-949e-fdce65351075',
  '721ef602-e376-4398-ae2e-4e556a472a4c',
  'dd31150d-a6fb-49db-934e-f6a7a43003f2',
  '9477ab21-6dc2-4f62-a72c-08b690c46c9b',
  '994ffcc4-02a4-4350-a00c-50a9715b7997',
  '00e17d64-3614-4eef-acab-4dff92758616',
  '59f27b88-0344-4d1e-a3d4-8b837c91fe50',
  '54f03528-49ac-4dc4-93e5-35a8bba38eed',
  'fc5233b6-ebc2-466d-8d19-a5ffe9e500a3',
  '1c78b01a-2ae6-4154-ab46-a7f198a98dc2',
  '861b2bb8-1e59-49c8-a41e-beff972f43b7',
  'fcfbec84-1079-4145-84b8-f3bfb92a6053',
  'c618f979-34a8-406d-80c5-5fc3136c250a',
  '98146fc9-46f1-4112-bbc9-99e2662b0805',
  '4ef76f06-34d0-4cd5-84b5-1e3d6fd24833',
  '405f3232-d881-4e02-8938-c6a8a2fc01cc',
  '1adff864-ef97-4fa9-9f0b-547ce507f14b',
  'c3611acf-b151-4563-854b-ee6424703df6',
  'd9dd8063-2970-4fcc-9e08-dcad551a5593',
  '145e2058-78ac-4ab1-bc30-ff42187b3c75',
  '4537c586-62fe-4708-beb8-ce4ef3f12ea6',
  '0b31f635-e895-42ce-8694-b82e14a68fef',
  'fc12ddca-de33-42fb-a6be-f2b55731aac9',
  'e9f8e099-7ebc-49d2-80a7-07d1b1852581',
  'd00bb008-f60c-4cd8-b23d-d7dd722bc3b1',
  '3d03513f-28c0-43d3-895c-9b68fdb8a773'],
 'merged_from_count': 41}

In [47]:
rels_france_1 = mgr.kg_relationships.find_by_entities(entity_ids=[ent_france_1.id], graph_name=graph_name)

In [48]:
for rel in rels_france_1:
    print(f"{rel.source_entity_name} --[{rel.relation_type}]--> {rel.target_entity_name}  (temporal: {rel.temporal_context or '-'})   (desc: {rel.description or '-'})")

Russia --[part_of]--> Europe  (temporal: 1900)   (desc: Russians made up a quarter of Europe's population in 1900.)
revolution in 1905 --[part_of]--> Russia  (temporal: 1905)   (desc: The 1905 revolution occurred within Russia.)
Japanese --[conquered]--> Russia  (temporal: -)   (desc: Japan defeated Russia in war, shaking the regime's confidence and contributing to the 1905 revolution.)
Russia --[opposed]--> Turkey  (temporal: 1876)   (desc: Russia and Turkey came to blows in 1876, marking the last war between European great powers in the nineteenth century.)
Russia --[participated_in]--> 1905 Revolution  (temporal: 1905)   (desc: Russia experienced a political revolution in 1905, marking deep internal change.)
Alexander II --[influenced]--> Russia  (temporal: late 19th century)   (desc: Alexander II's reforms promised liberal change in Russia but were undermined by autocracy and terrorism.)
Russia --[conquered]--> serfdom  (temporal: -)   (desc: Serfdom was abolished in Russia, removing restraints on individualism to promote prosperous independent farmers.)
autocracy --[ruled]--> Russia  (temporal: early twentieth century)   (desc: The autocracy governed Russia badly and opposed all change in the early twentieth century.)
Russia --[part_of]--> United Kingdom  (temporal: -)   (desc: Russia produced less than a third as much pig-iron as the United Kingdom in 1910, indicating industrial comparison rather than political part-of relationship, so this relation is omitted.)
Russia --[part_of]--> Germany  (temporal: -)   (desc: Russia produced about a quarter as much steel as Germany in 1910, indicating industrial comparison rather than political part-of relationship, so this relation is omitted.)
France --[allied_with]--> United Kingdom  (temporal: -)   (desc: France allied with the United Kingdom as part of the liberal and constitutional powers in Europe.)
France --[allied_with]--> Italy  (temporal: -)   (desc: France allied with Italy as part of the liberal and constitutional powers in Europe.)
Third Republic --[part_of]--> France  (temporal: -)   (desc: The Third Republic was the government of France representing liberal and constitutional principles.)
German army --[opposed]--> France  (temporal: 1870)   (desc: The German army defeated France in 1870, demonstrating French military inferiority.)
France --[opposed]--> German army  (temporal: just before 1914)   (desc: France was aware of its military inferiority to Germany and sought allies for a potential future conflict.)
France --[opposed]--> United Kingdom  (temporal: 1900)   (desc: France came into irritating conflict with the United Kingdom in many colonial regions around the globe.)
Russia --[opposed]--> United Kingdom  (temporal: 1900)   (desc: Russia came into irritating conflict with the United Kingdom in many colonial regions around the globe.)
United Kingdom --[opposed]--> France  (temporal: 1900)   (desc: The United Kingdom was in conflict with France over colonial issues around 1900.)
United Kingdom --[opposed]--> Russia  (temporal: 1900)   (desc: The United Kingdom was in conflict with Russia over colonial issues around 1900.)
Japan --[conquered]--> Russia  (temporal: -)   (desc: Japan achieved a military victory over Russia, signaling its emergence as a great power.)
United States --[succeeded]--> Russia  (temporal: 1914)   (desc: The United States had a political constitution older than most European states except Great Britain and Russia, indicating a succession in political development.)
European balance --[influenced]--> Russia  (temporal: before 1914)   (desc: The European balance kept peace involving Russia until it was disturbed by 1914.)
Germany --[opposed]--> Russia  (temporal: by 1914)   (desc: Ruling circles of Germany and Russia felt that war might offer more than peace, contributing to instability.)
Austria-Hungary --[opposed]--> Russia  (temporal: by 1914)   (desc: Ruling circles of Austria-Hungary and Russia felt that war might offer more than peace, contributing to instability.)
Austria-Hungary --[opposed]--> Russia  (temporal: -)   (desc: Austria-Hungary and Russia had a long-standing rivalry in south-eastern Europe culminating in conflicts leading up to 1914.)
Russia --[opposed]--> Ottoman empire  (temporal: post-Crimean War)   (desc: Russian interest in the Danube valley revived after the Crimean War, opposing the Ottoman empire's control.)
Russia --[opposed]--> Austria-Hungary  (temporal: 1909)   (desc: Russia was offended and humiliated by Austria-Hungary's annexation of Bosnia without compensating gains.)
Russia --[allied_with]--> Serbia  (temporal: -)   (desc: Russia stood behind Serbia and supported its position against Austria-Hungary.)
Bismarck --[influenced]--> France  (temporal: 1870s and 1880s)   (desc: Bismarck's efforts aimed to isolate France through a system of alliances in the 1870s and 1880s.)
Germany --[opposed]--> France  (temporal: 1871)   (desc: Germany's seizure of Alsace and Lorraine caused French restlessness for revenge.)
Bismarck --[allied_with]--> Russia  (temporal: post-1871)   (desc: Bismarck drew together Germany, Russia, and Austria-Hungary on dynastic resistance grounds.)
Bismarck --[allied_with]--> Russia  (temporal: post-1882)   (desc: Bismarck maintained a separate 'Reinsurance' treaty with Russia to keep peace between Russia and Austria-Hungary.)
Austria --[opposed]--> Russia  (temporal: twentieth century)   (desc: Austria was likely to be at war with Russia.)
Germany --[opposed]--> Russia  (temporal: by 1900)   (desc: Germany opposed Russia by preparing for a two-front war involving a quick overthrow of France while Russia mobilized.)
Russia --[allied_with]--> France  (temporal: 1892)   (desc: Russia became an ally of France in 1892.)
France --[allied_with]--> Austria  (temporal: twentieth century)   (desc: France was likely to join Austria in a war against Russia.)
Germany --[opposed]--> France  (temporal: 1905 and 1911)   (desc: Germany showed irritation and used commercial and colonial issues to display force against France in 1905 and 1911.)
Russia --[opposed]--> Turkey  (temporal: twentieth century)   (desc: Russia was alarmed by Germany's patronage of Turkey due to control of strategic straits affecting Russian grain exports.)
Russia --[part_of]--> Black Sea  (temporal: -)   (desc: Russia had ports on the Black Sea critical for grain export.)
Great Britain --[opposed]--> France  (temporal: end of the nineteenth century)   (desc: Great Britain had imperial quarrels with France in Africa and central and south-eastern Asia.)
Great Britain --[opposed]--> Russia  (temporal: end of the nineteenth century)   (desc: Great Britain had imperial quarrels with Russia in Africa and central and south-eastern Asia.)
Great Britain --[allied_with]--> France  (temporal: 1904)   (desc: In 1904, Great Britain and France settled long outstanding disputes, agreeing that France would have a free hand in Morocco and Great Britain in Egypt.)
Russia --[opposed]--> Persia  (temporal: -)   (desc: Russia had spheres of interest in Persia, implying opposition or contest over influence.)
Germany --[opposed]--> France  (temporal: -)   (desc: Germany challenged France's influence in Morocco by forcing an international conference to assert its say in Moroccan affairs.)
Germany --[opposed]--> France  (temporal: 1911)   (desc: In 1911, German diplomacy provoked another crisis over Morocco, escalating tensions with France and Britain.)
Great Britain --[allied_with]--> France  (temporal: -)   (desc: The Anglo-French entente was solidified as Britain realized the need to counterbalance Germany's continental ambitions.)
Russia --[allied_with]--> Serbia  (temporal: -)   (desc: Russia supported Serbia and was rebuilding and expanding its forces to back Serbia.)
Germany --[opposed]--> Russia  (temporal: -)   (desc: Germany was unlikely to avoid fighting Russia while confident of winning.)
Austria-Hungary --[opposed]--> Russia  (temporal: 6 August 1914)   (desc: Austria-Hungary declared war on Russia, its old rival, on 6 August 1914.)
Germany --[opposed]--> Russia  (temporal: 1914)   (desc: Germany declared war on Russia after Russia mobilized to protect Serbia.)
Germany --[opposed]--> France  (temporal: 1914)   (desc: Germany declared war on France and attacked through Belgium as part of its military plan.)
Russia --[allied_with]--> France  (temporal: 1914)   (desc: France and Russia had an alliance, but it never operated effectively during the war's outbreak.)
Japan --[allied_with]--> Allies  (temporal: -)   (desc: Japan joined the Allies soon after the outbreak of the war.)
Italy --[allied_with]--> Allies  (temporal: 1915)   (desc: Italy joined the Allies in 1915 in return for promises of Austrian territory.)
Romania --[allied_with]--> Allies  (temporal: 1916)   (desc: Romania joined the Allies in 1916.)
Greece --[allied_with]--> Allies  (temporal: 1917)   (desc: Greece became an Ally in 1917.)
Germany --[conquered]--> France  (temporal: 1914-1915)   (desc: Germany occupied much French territory after the initial offensive in northern France.)
France --[participated_in]--> World War I  (temporal: 1914-1916)   (desc: France fought in the war, suffering heavy casualties and losing territory.)
Allies --[opposed]--> Turkey  (temporal: 1915)   (desc: The Allies attacked Turkey at the Dardanelles in 1915 to try to knock her out of the war and open communication with Russia.)
Serbia --[conquered]--> Allies  (temporal: -)   (desc: Serbia was overrun, causing the collapse of the Balkan front previously held by the Allies.)
British Empire --[part_of]--> Allies  (temporal: -)   (desc: The British Empire was part of the Allies and conducted operations in Mesopotamia and towards Palestine.)
Allies --[part_of]--> Allies  (temporal: -)   (desc: The Allies mounted a new Balkan front at Salonika after the collapse of the Serbian front.)
United States --[allied_with]--> Allies  (temporal: -)   (desc: The United States was accessible to the Allies during the war.)
Japan --[allied_with]--> Allies  (temporal: -)   (desc: Japan was accessible to the Allies during the war.)
British empire --[part_of]--> Allies  (temporal: 1914-1918)   (desc: The British empire was part of the Allies during the war, as indicated by its hospital bed statistics.)
Allies --[conquered]--> United States  (temporal: -)   (desc: The Allies liquidated their investments in the United States to pay for their needs, becoming debtors themselves.)
Allied governments --[influenced]--> United States  (temporal: 1914)   (desc: Allied propaganda and war aims helped shift American opinion in favor of the Allies.)
Allies --[allied_with]--> Great Britain  (temporal: 1917)   (desc: Great Britain was part of the Allies during World War I.)
Allies --[allied_with]--> France  (temporal: 1917)   (desc: France was part of the Allies during World War I.)
Russian empire --[opposed]--> Allies  (temporal: 1917)   (desc: The Russian empire was part of the Allied powers but collapsed in 1917, ceasing to be a great power.)
German armies --[opposed]--> Russian state  (temporal: February 1917)   (desc: German armies broke the morale of Russian soldiers leading to the destruction of the Russian state.)
February 1917 Revolution --[succeeded]--> Russian state  (temporal: February 1917)   (desc: The revolution marked the destruction of the Russian state and the start of revolutionary transformation.)
tsar --[ruled]--> Russian state  (temporal: -)   (desc: The tsar was the autocratic ruler of Russia before abdicating during the revolution.)
USSR --[succeeded]--> tsarist state  (temporal: post-1917)   (desc: The USSR succeeded the tsarist state after the revolution.)
USSR --[opposed]--> tsarist state  (temporal: post-1917)   (desc: The USSR renounced all extraterritorial rights and jurisdictions enjoyed by the tsarist state, indicating opposition to the old regime.)
French --[opposed]--> Vietnamese revolt  (temporal: 1930)   (desc: The French opposed the Vietnamese nationalist revolt in 1930, which had Communist support.)
Japanese --[opposed]--> French  (temporal: 1939)   (desc: The Japanese occupiers brushed aside protests from the French and prepared to blockade foreign settlements if their new order was not recognized.)
Japan --[opposed]--> French  (temporal: -)   (desc: Japan forced the French to admit an occupying army to Indochina.)
Indochina --[part_of]--> French  (temporal: -)   (desc: Indochina was a region under French control where Japan established an occupying army.)

### Second occurance

In [49]:
ent_france_2 = top_entities[6]

In [50]:
ent_france_2.__dict__

{'id': '4286e4e7-a53e-4856-a3ff-016337a38c29',
 'graph_name': 'book7_ch0-6',
 'name': 'France',
 'entity_type': 'polity',
 'aliases': ['French', 'French Empire', 'French empire'],
 'descriptions': ['One of the powers with which China had unequal treaties that were swept away during the Second World War.',
  'French armed forces later admitted to Berlin administration after Soviet agreement.',
  'Colonial power contrasted with British in terms of concessions to nationalist sentiment.',
  'Colonial power in South-East Asia with colonies affected by World War II.',
  'Colonial power in Indochina attempting to maintain control after WWII.',
  'Colonial power trying to retain a diminished Vietnam and other Indochinese states within the French Union.',
  'A great power that held League of Nations mandates in Syria and Lebanon until 1939.',
  'Tried to re-establish authority in Syria and Lebanon after the war and faced nationalist movements in Algeria.',
  'French colonial possessions where De Gaulle hoped to find sympathizers to continue the fight.',
  "A European country whose language and cultural influence spread in Egypt during Muhammad Ali's reforms.",
  'Country where Ismail was educated and whose people and ideas he favored.',
  'Had a special role and interests in the Levant and Middle East, including protection of Catholicism in the Ottoman Empire.',
  'A major Allied power with special interests in Syria, involved in agreements on Ottoman empire partition.',
  'One of the great powers engaged in the Middle East, awarded mandate for Syria and governed it forcefully.',
  'A colonial power whose brutality in Syria caused Arab resentment.',
  'One of the Allied powers that agreed on shares of the Ottoman territory and established spheres of influence.',
  'One of the powers driven out by Mustafa Kemal.',
  'A major western European power reconstituted after occupation and defeat, with a strengthened Communist Party.',
  'A country overshadowed by a united Germany in central Europe.',
  'A European country seeking allies against a German revival in eastern and central Europe.',
  'A western European great power, militarily weak, invested in strategic defense by fortification against Germany.',
  "A great power and African colonial power involved in the League of Nations' response to Italy's invasion of Ethiopia.",
  'Country with a large and active Communist Party, but where Communist aims were not accepted by the majority after the Depression.',
  'Western power that might have encouraged a German attack on the USSR and declared war on Germany after the invasion of Poland.',
  'One of the two constitutional great powers of Europe responding to German expansion.',
  'Country invaded and defeated by Germany, signing an armistice on 22 June.',
  'Country with a faction in exile during the war.',
  'The country whose interests and honour he was custodian of.',
  'A great power involved in nationalist disputes over Alsace and Lorraine.',
  'A nation where anti-clericalism and priest-baiting were significant political issues in the late 19th century.',
  'Victorious power concerned about German aggression, central to European security issues.',
  'A major belligerent suffering heavy casualties.',
  'A major Allied power during World War I.',
  'The French state seeking to impose harsh terms on Germany to prevent future wars and ensure security.',
  'A major country whose currency remained on the gold standard by 1933.'],
 'occurrence_count': 35,
 'book_indices': [7],
 'source_book_chapters': ['7:1', '7:2', '7:4', '7:5', '7:6'],
 'source_pages': [1249,
  1252,
  1281,
  1282,
  1286,
  1289,
  1307,
  1334,
  1336,
  1343,
  1344,
  1345,
  1348,
  1349,
  1357,
  1358,
  1361,
  1363,
  1368,
  1369,
  1370,
  1371,
  1372,
  1382,
  1393,
  1399,
  1406,
  1410,
  1411,
  1412,
  1413],
 'source_paragraph_ids': ['67b42ac4-1919-4dce-aaf4-0cefc1bf1a4c',
  'a8e99da6-2e8c-455d-8071-838f73e269a8',
  '2f33dcff-5a1f-47f0-a180-6027e3c17d73',
  'b89309d9-07dc-4468-87c1-474cb7ec92b6',
  '5b663eb2-13bc-4e88-81e8-a8206e8159f6',
  'c6dd44ea-a64d-4fb4-97ba-9a36a9848a9e',
  'e9ff1e16-65d8-413a-8a86-4ea4543252a6',
  '9c5cccf3-5710-4c1f-8bbc-fc78b299e317',
  '62934249-9d8e-4fb6-89da-335716925c88',
  '08035707-4d15-4483-b1e9-6ffc383e4f74',
  'f2803256-51f5-41a0-b45f-b09d7bf8bf6e',
  'c3a3774d-ed71-4f5a-8649-2391857a11d1',
  '0e8077b1-4f48-402f-a977-495c7488ad2e',
  '58fc0cb3-f0d9-4572-b167-b527d7f88f14',
  '6531b863-63f6-45b2-9184-7b4c296090d0',
  '3ead5a87-a737-44ba-99c1-03a10cb4fc3f',
  '94901470-f05b-4c79-911c-aa07594cdf53',
  '5eef4fa7-b204-4910-a677-c8747e3d3b88',
  '268edb86-1b62-425d-bc72-d2ca7b351382',
  'c31bfaaa-a5fc-4ab8-8277-c17f16165045',
  '4bec8ea5-7a46-4327-9f8c-8f176743ae43',
  '0a5d4c51-4361-4419-9078-5b4d44b82593',
  '4d65bdee-ec03-4e5d-a5fc-a19a0c63b7a8',
  '4ba5711e-6106-4f83-8665-5abcbfa1c4cb',
  '5488505c-7105-4a44-8e59-63554ef4b4a0',
  '7438b1b8-15de-498c-90de-dbe6856ddc13',
  '0261abd1-f37e-4c49-9036-ad6853bb6b84',
  'c2228e83-c5ed-494b-86e3-b8f0fc52bd02',
  'b8211064-0999-4fe4-ae3b-9bdbc4fdd350',
  '0d760c7a-706e-4166-9562-013b872cb4b1',
  'c8237fcd-3ff3-409a-a169-70663ed83c63',
  '4607e45b-f317-43b9-84a8-d7c317d5c62a',
  '25edb149-1b00-4804-b641-241c2f9297b5',
  'dd370dd6-15a5-4978-a191-b83081089a7a',
  '35db43d1-653f-41c2-a51c-3629e89f0ccd'],
 'merged_from_count': 35}

In [51]:
rels_france_2 = mgr.kg_relationships.find_by_entities(entity_ids=[ent_france_2.id], graph_name=graph_name)

In [52]:
for rel in rels_france_2:
    print(f"{rel.source_entity_name} --[{rel.relation_type}]--> {rel.target_entity_name}  (temporal: {rel.temporal_context or '-'})   (desc: {rel.description or '-'})")

France --[opposed]--> Germany  (temporal: post-1871)   (desc: France opposed Germany due to the loss of Alsace and Lorraine and cultivated the theme of revanche.)
France --[opposed]--> Church  (temporal: 1870-1890)   (desc: Anti-clericalism and priest-baiting were important political issues opposing the Church.)
Germany --[opposed]--> France  (temporal: -)   (desc: Germany was fighting France on one of its two fronts and had suffered heavy casualties.)
Allies --[allied_with]--> France  (temporal: 1917)   (desc: France was part of the Allies during World War I.)
Passchendaele --[participated_in]--> France  (temporal: 1917)   (desc: The battles of Passchendaele took place in France in 1917.)
French army --[part_of]--> France  (temporal: 1917)   (desc: The French army was the military force of France during World War I.)
France --[opposed]--> Germany  (temporal: -)   (desc: France was aware of the danger of German aggression and was a central actor in European security concerns.)
United States --[allied_with]--> France  (temporal: 1918)   (desc: United States allied with France as part of the principal victorious powers.)
France --[opposed]--> Germany  (temporal: -)   (desc: France imposed harsh punitive settlement terms on Germany to prevent any future German wars.)
France --[conquered]--> Alsace and Lorraine  (temporal: -)   (desc: France regained control of Alsace and Lorraine from Germany as part of territorial losses.)
France --[opposed]--> Germany  (temporal: -)   (desc: France demanded economic reparations from Germany to tie it down and prevent future wars, which angered Germans.)
France --[opposed]--> Germany  (temporal: -)   (desc: France insisted on the demilitarization of the German bank of the Rhine as a security measure.)
France --[ruled]--> gold standard  (temporal: by 1933)   (desc: France was the only major country to keep its currency on the gold standard by 1933.)
France --[influenced]--> Egypt  (temporal: early 19th century)   (desc: French language and culture became prominent in Egypt, with French becoming the second language of educated Egyptians and a large French community in Alexandria.)
Ismail --[influenced]--> France  (temporal: -)   (desc: Ismail was educated in France and favored French people and modern ideas.)
French Empire --[part_of]--> Levant  (temporal: -)   (desc: France claimed a special role and cultural predominance in the Levant, including protection of Catholicism.)
Napoleon III --[ruled]--> French Empire  (temporal: 1860s)   (desc: Napoleon III was the French leader who sent an army to Syria in the 1860s.)
British --[allied_with]--> French  (temporal: -)   (desc: The British and French agreed on spheres of influence in a partitioned Ottoman empire.)
France --[allied_with]--> League of Nations  (temporal: -)   (desc: France, with the help of the League of Nations, laid out the map of the modern Arab world.)
Arab peoples --[opposed]--> France  (temporal: 1930s)   (desc: Arab peoples faced French governance and launched a full-scale insurrection against French rule in Syria.)
Kurdish people --[opposed]--> France  (temporal: -)   (desc: The Kurdish people of north Syria revolted against the prospect of submergence in an Arab state under French mandate.)
Mustafa Kemal --[conquered]--> France  (temporal: -)   (desc: Mustafa Kemal drove out the French after frightening away the Italians.)
sultan --[opposed]--> French  (temporal: -)   (desc: The sultan faced French invasion leading to a humiliating peace.)
France --[opposed]--> Syria  (temporal: -)   (desc: Arab resentment was growing due to French brutality in Syria.)
British --[allied_with]--> French  (temporal: -)   (desc: The British and French were allied powers agreeing on shares of Ottoman territory.)
French --[allied_with]--> Greeks  (temporal: -)   (desc: The French and Greeks were allied powers agreeing on shares of Ottoman territory.)
Germany --[opposed]--> France  (temporal: 1930s)   (desc: Germany's dominance in central Europe overshadowed France, indicating a fundamental issue of power balance.)
French --[allied_with]--> Italians  (temporal: -)   (desc: The French and Italians were allied powers agreeing on shares of Ottoman territory.)
France --[allied_with]--> Germany  (temporal: 1930s)   (desc: France sought allies against a German revival in eastern and central Europe but these allies were weakened in the 1930s.)
USSR --[opposed]--> France  (temporal: 1930s)   (desc: Ideological distinctions presented barriers to cooperation between the USSR and France in containing Germany.)
Great Britain --[allied_with]--> France  (temporal: post-1918)   (desc: Great Britain and France had been much at odds since 1918 but were the main powers to confront Germany in absence of USSR and USA.)
France --[opposed]--> Germany  (temporal: -)   (desc: France was a western European power prepared to confront Germany, investing in strategic defense due to manpower inferiority.)
France --[allied_with]--> Great Britain  (temporal: 1935)   (desc: France and Great Britain were bound to take the lead against Italy at the League of Nations due to their status as great powers and African colonial powers.)
France --[opposed]--> Italy  (temporal: 1935)   (desc: France opposed Italy's invasion of Ethiopia but did so feebly to avoid alienating Italy.)
Communist Party --[part_of]--> France  (temporal: post-Depression)   (desc: The Communist Party was large and active in France but lacked majority electoral support after the Depression.)
France --[opposed]--> Germany  (temporal: 3 September 1939)   (desc: France declared war on Germany after the invasion of Poland, honoring its guarantee to Poland.)
France --[opposed]--> German forces  (temporal: -)   (desc: France responded to the danger presented by Germany's expansion.)
France --[succeeded]--> Vichy government  (temporal: June 1940)   (desc: The Vichy government succeeded the Third Republic after the armistice with Germany.)
Charles de Gaulle --[ruled]--> France  (temporal: -)   (desc: Charles de Gaulle led the French exiled faction, representing a faction within France but not its legal government.)
Free French --[part_of]--> France  (temporal: -)   (desc: The Free French represented the interests of France during the period.)
De Gaulle --[influenced]--> French empire  (temporal: -)   (desc: De Gaulle hoped to find sympathizers in parts of the French empire to join him in continuing the fight.)
French --[conquered]--> Bismarck’s creation  (temporal: -)   (desc: The French occupied a zone of Germany after WWII.)
French --[opposed]--> Communist Party  (temporal: -)   (desc: France had a much strengthened Communist Party committed to revolutionary overthrow of capitalism.)
Soviets --[allied_with]--> French  (temporal: -)   (desc: Soviets later admitted French armed forces to Berlin administration as per agreement.)
Algeria --[opposed]--> French Empire  (temporal: -)   (desc: Bitter warfare occurred between the colonial state and indigenous peasantry in Algeria.)
Indochina --[opposed]--> French Empire  (temporal: -)   (desc: Bitter warfare occurred between the colonial state and indigenous peasantry in Indochina.)
Indochina --[opposed]--> French Empire  (temporal: -)   (desc: Nationalist sentiment and organization existed before the departure of French imperial rulers in Indochina.)
China --[allied_with]--> France  (temporal: Second World War)   (desc: China's unequal treaties with France were swept away during the Second World War, improving relations.)
Second World War --[opposed]--> French  (temporal: -)   (desc: The war ended French colonial rule in South-East Asia decisively and bloodily.)
French --[allied_with]--> British  (temporal: -)   (desc: The British cooperated with the French in attempting to re-establish French control in Indochina.)
French --[opposed]--> Viet Minh  (temporal: end of 1946)   (desc: French soldiers were attacked by Viet Minh forces and eventually bombarded Hanoi, forcing Ho Chi Minh's government to flee.)
French --[ruled]--> Hanoi  (temporal: end of 1946)   (desc: French troops reoccupied Hanoi after bombardment in 1946.)
Communists --[opposed]--> French  (temporal: -)   (desc: Communists struggled against the French to achieve a united country in Indochina.)
French --[conquered]--> Vietnam  (temporal: by 1949)   (desc: French tried to retain a diminished Vietnam including Cochin-China by 1949.)
French --[conquered]--> Cochin-China  (temporal: by 1949)   (desc: French included Cochin-China in Vietnam by 1949.)
French --[conquered]--> Cambodia  (temporal: by 1949)   (desc: French recognized Cambodia as an associate state by 1949.)
French --[conquered]--> Laos  (temporal: by 1949)   (desc: French recognized Laos as an associate state by 1949.)
France --[ruled]--> Syria  (temporal: 1939)   (desc: France held the League of Nations mandate in Syria until 1939.)
France --[ruled]--> Lebanon  (temporal: 1939)   (desc: France held the League of Nations mandate in Lebanon until 1939.)
France --[opposed]--> Syria  (temporal: post-1945)   (desc: France tried unsuccessfully to re-establish authority in Syria after the war.)
France --[opposed]--> Lebanon  (temporal: post-1945)   (desc: France tried unsuccessfully to re-establish authority in Lebanon after the war.)
France --[opposed]--> Algeria  (temporal: 1945)   (desc: France faced fighting in Algeria in 1945 with nationalists seeking autonomy.)
Algeria --[opposed]--> France  (temporal: 1945)   (desc: Nationalists in Algeria fought against French authority in 1945, seeking autonomy.)

# Check vectors

In [2]:
from history_book.database.config.database_config import WeaviateConfig
from history_book.database.repositories.book_repository import BookRepositoryManager

config = WeaviateConfig.from_environment()
mgr = BookRepositoryManager(config)

# Quick counts
print(f"KG Entities:       {mgr.kg_entities.count()}")
print(f"KG Relationships:  {mgr.kg_relationships.count()}")
print(f"KG Graphs:         {mgr.kg_graphs.count()}")

# What graphs do we have?
for g in mgr.kg_graphs.list_all():
    print(f"\n  {g.name} ({g.graph_type}): {g.entity_count} entities, {g.relationship_count} rels, chapters={g.book_chapters}")

KG Entities:       247
KG Relationships:  457
KG Graphs:         1

  book3_ch2-3 (book): 247 entities, 457 rels, chapters=['3:2', '3:3']

In [3]:
# Which graph has this paragraph? Use the merged book graph.
graph_name = "book3_ch2-3"

In [4]:
mgr.kg_entities.search_entities(query_text="Parthia", graph_name=graph_name)

[(KGEntity(id='da8c0473-13a4-4e48-959c-c69627055aaf', graph_name='book3_ch2-3', name='Parthian Empire', entity_type='polity', aliases=['Parthia (Parthian Empire)', 'Parthia'], descriptions=['Empire established by Mithridates I, stretching from Bactria in the east to Babylonia in the west.', 'An Iranian nomadic people who created political unity in Iran and Mesopotamia and were known for mounted archery.', 'A kingdom in the east that emerged as a new threat and an important satrapy south-east of the Caspian Sea.', 'A polity located on the Euphrates, facing a new power from the west.'], occurrence_count=4, book_indices=[3], source_book_chapters=['3:3'], source_pages=[312, 313], source_paragraph_ids=['01f84f6a-0902-49f7-ab19-fa9343e44aed', 'e531a0c6-ba46-4aad-8994-013584ffe079', '00e27974-33f2-4e98-aab0-e97511ccdb82', 'b9b8b555-088a-4da9-a46f-db3112ff31bc'], merged_from_count=4),
  0.7157468795776367),
 (KGEntity(id='ecf03ced-fc1e-42ef-8570-086133bfe0cf', graph_name='book3_ch2-3', name='Mesopotamia', entity_type='place', aliases=[], descriptions=['A region where the Parthians established political unity.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[312], source_paragraph_ids=['01f84f6a-0902-49f7-ab19-fa9343e44aed'], merged_from_count=1),
  0.5949041247367859),
 (KGEntity(id='b8597aa0-b22c-484e-b36e-87e52e1dbaf9', graph_name='book3_ch2-3', name='Armenia', entity_type='polity', aliases=[], descriptions=['Northern satrapy whose rulers did homage to Alexander.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[305], source_paragraph_ids=['2c21c9fc-6685-4098-941c-056c46ff264b'], merged_from_count=1),
  0.5665764808654785),
 (KGEntity(id='ea432ab1-efd8-4148-86e4-1802b3318220', graph_name='book3_ch2-3', name='Iran', entity_type='place', aliases=[], descriptions=['A highland region where the Parthians established political unity.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[312], source_paragraph_ids=['01f84f6a-0902-49f7-ab19-fa9343e44aed'], merged_from_count=1),
  0.532776951789856),
 (KGEntity(id='b7ee88e5-8650-45ad-a7b3-b320eba364a6', graph_name='book3_ch2-3', name='Bithynia', entity_type='polity', aliases=[], descriptions=['Northern satrapy whose rulers did homage to Alexander.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[305], source_paragraph_ids=['2c21c9fc-6685-4098-941c-056c46ff264b'], merged_from_count=1),
  0.5307328104972839),
 (KGEntity(id='05dc95e2-6399-40d1-a8fa-dc718240c584', graph_name='book3_ch2-3', name='Mithridates I', entity_type='person', aliases=[], descriptions=["Younger of two brothers who established the Parthian empire in the second century BC, styled himself as 'Great King'."], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[313], source_paragraph_ids=['b9b8b555-088a-4da9-a46f-db3112ff31bc'], merged_from_count=1),
  0.5266919136047363),
 (KGEntity(id='94734b4d-3f11-4dce-87d8-2ca13d5ba92b', graph_name='book3_ch2-3', name='Cappadocia', entity_type='polity', aliases=[], descriptions=['Northern satrapy whose rulers did homage to Alexander.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[305], source_paragraph_ids=['2c21c9fc-6685-4098-941c-056c46ff264b'], merged_from_count=1),
  0.5200455188751221),
 (KGEntity(id='9f949970-6b42-4830-81ee-a573c3d5e66f', graph_name='book3_ch2-3', name='western satraps', entity_type='polity', aliases=[], descriptions=['Provincial governors who led a major revolt against Persian rule.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[297], source_paragraph_ids=['9e6baedf-5245-4429-9884-ed105da26c77'], merged_from_count=1),
  0.5161462426185608),
 (KGEntity(id='fd491a2d-6f75-4f91-97be-6b1613866006', graph_name='book3_ch2-3', name='Arsacid dynasty', entity_type='polity', aliases=[], descriptions=['Dynasty to which Mithridates I and II belonged, consciously related to the Achaemenid Persian line.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[313], source_paragraph_ids=['b9b8b555-088a-4da9-a46f-db3112ff31bc'], merged_from_count=1),
  0.510032057762146),
 (KGEntity(id='7872cecb-9e44-4a18-be80-b4d155acba46', graph_name='book3_ch2-3', name='Kingdom of Pergamon', entity_type='polity', aliases=[], descriptions=['A kingdom formed from part of the Seleucid Empire after Celtic invasions, ruled by the Attalid dynasty.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[306], source_paragraph_ids=['c899da96-aba2-492f-8977-02dabaa18fd9'], merged_from_count=1),
  0.4930974245071411),
 (KGEntity(id='7c38eafb-9115-4862-8849-3d9e0efee395', graph_name='book3_ch2-3', name='Persian officials', entity_type='polity', aliases=[], descriptions=['Officials through whom Alexander ruled conquered areas.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[302], source_paragraph_ids=['2975d6e7-a940-40fc-b553-430fa8ae689e'], merged_from_count=1),
  0.4822896718978882),
 (KGEntity(id='a1bb5e99-257b-48b4-9733-cc8639c0704f', graph_name='book3_ch2-3', name='Mithridates II', entity_type='person', aliases=[], descriptions=["Successor to Mithridates I who recovered lost ground and expanded the Parthian empire further, bearing the title 'King of Kings'."], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[313], source_paragraph_ids=['b9b8b555-088a-4da9-a46f-db3112ff31bc'], merged_from_count=1),
  0.4806109070777893),
 (KGEntity(id='8a6e43ef-c146-4fc8-8d19-50ed987f90f9', graph_name='book3_ch2-3', name='nomads from the steppes', entity_type='polity', aliases=[], descriptions=['Nomadic groups threatening the north-east region of the Seleucid kingdom.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[312], source_paragraph_ids=['00e27974-33f2-4e98-aab0-e97511ccdb82'], merged_from_count=1),
  0.479910671710968),
 (KGEntity(id='62bc41af-c8fa-420b-b509-195d1c4a3ca5', graph_name='book3_ch2-3', name='Darius', entity_type='person', aliases=[], descriptions=['A Persian leader who employed a Greek physician.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:2'], source_pages=[265], source_paragraph_ids=['c10eb7d6-3c79-469d-8ed2-5247e8b41e8b'], merged_from_count=1),
  0.43635547161102295),
 (KGEntity(id='dd695cc5-3902-4694-87e2-a9802f80d609', graph_name='book3_ch2-3', name='Tyre', entity_type='polity', aliases=[], descriptions=['A city-state surpassed by Carthage in wealth and power.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[314], source_paragraph_ids=['37883ea1-6750-4aaa-917b-735601ef2931'], merged_from_count=1),
  0.435599148273468),
 (KGEntity(id='38abc64a-179c-4b50-a20f-2fdec6f12987', graph_name='book3_ch2-3', name='Cyrus', entity_type='person', aliases=[], descriptions=['A Persian leader who employed Greek stone-cutters and sculptors.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:2'], source_pages=[265], source_paragraph_ids=['c10eb7d6-3c79-469d-8ed2-5247e8b41e8b'], merged_from_count=1),
  0.4306507110595703),
 (KGEntity(id='2a6edfa7-285f-454d-9dfb-360c1b6bd81e', graph_name='book3_ch2-3', name='Rhodes', entity_type='polity', aliases=[], descriptions=['An ally of Athens that placed itself under Macedonian patronage.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[299], source_paragraph_ids=['75726c0d-3980-46cf-a09d-fd7b01596cf2'], merged_from_count=1),
  0.42897647619247437),
 (KGEntity(id='6725c95f-5a14-4580-b815-d404ae418a3b', graph_name='book3_ch2-3', name='Antigonids', entity_type='polity', aliases=[], descriptions=['A dynasty ruling Macedon during the period of contest for Greek states.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[306], source_paragraph_ids=['d4d3ed3a-faf1-41ef-b1ab-c8d939f2912f'], merged_from_count=1),
  0.42720526456832886),
 (KGEntity(id='700651a6-4f9a-4d74-bdd0-42e23da216e6', graph_name='book3_ch2-3', name='Phrygia', entity_type='polity', aliases=[], descriptions=['A polity through which Lydia indirectly acquired the alphabet from Greece.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:2'], source_pages=[257], source_paragraph_ids=['ab3b0165-9408-463f-92fa-f2658486f1f2'], merged_from_count=1),
  0.4262498617172241),
 (KGEntity(id='8cb27f83-47de-4375-8059-ed5d034a09a4', graph_name='book3_ch2-3', name='Seleucid Empire', entity_type='polity', aliases=['Asian empire', 'Seleucid kingdom'], descriptions=['A dynasty whose administrative structure was inherited by the Parthians.', 'Dynasty that founded or re-founded most Greek cities in Asia and controlled them through bureaucracy and mercenary armies.', 'A Hellenistic empire that united Hellenistic and oriental civilization, founded cities, and ruled over a heterogeneous hinterland including tribes, Persian satrapies, and vassal princes.', 'A dynasty contesting control of Greek states in Asia Minor.', 'A huge kingdom stretching from Afghanistan to Syria, ruled by descendants of Seleucus.', 'A Hellenistic kingdom weakened by concentration of population and wealth in its western half, distracted by conflicts with other Hellenistic states and Ptolemaic Egypt.'], occurrence_count=6, book_indices=[3], source_book_chapters=['3:3'], source_pages=[306, 307, 309, 312], source_paragraph_ids=['c899da96-aba2-492f-8977-02dabaa18fd9', 'd4d3ed3a-faf1-41ef-b1ab-c8d939f2912f', '01f84f6a-0902-49f7-ab19-fa9343e44aed', '7c079089-349b-4ea4-9921-1fd4c105a6ba', '55af6a7d-327d-40d8-b0d5-703d36919593', '00e27974-33f2-4e98-aab0-e97511ccdb82'], merged_from_count=6),
  0.42474818229675293),
 (KGEntity(id='24be22f5-0af2-45f2-a0a5-e7fe884658b2', graph_name='book3_ch2-3', name='Ptolemaic Egypt', entity_type='polity', aliases=["Ptolemy's province"], descriptions=["The longest-lived and richest of the successor states ruled by Ptolemy's descendants for nearly 300 years until 30 BC.", 'A Hellenistic kingdom involved in quarrels with the Seleucid kingdom.'], occurrence_count=2, book_indices=[3], source_book_chapters=['3:3'], source_pages=[306, 312], source_paragraph_ids=['c899da96-aba2-492f-8977-02dabaa18fd9', '00e27974-33f2-4e98-aab0-e97511ccdb82'], merged_from_count=2),
  0.42194831371307373),
 (KGEntity(id='91295353-9c8c-4c2a-9ff1-1b0d737d49cf', graph_name='book3_ch2-3', name='Achaemenid Persians (Achaemenid Empire)', entity_type='polity', aliases=['Achaemenids', 'Persians', 'Persian power', 'Persia'], descriptions=['Formidable eastern polity looming beyond Lydia.', 'Empire that took Egypt in 525.', 'A major polity engaged in conflict with Greece, employing Greek individuals in its fleets and armies.', 'A major empire that expanded greatly under the Achaemenids, conquering Lydia, Egypt, and parts of Europe.', 'The polity that sent fleets against the Greeks after the Ionian revolt.', 'The empire opposed by Greek city-states including Athens and Sparta in multiple conflicts.', 'Persian army invading Greece in 480 BC', 'A polity opposed and defeated by the Greeks.', 'Enemy in the ongoing war; target of liberation efforts by Athens and the Delian League.', 'An empire that previously held Greek cities of mainland Asia as vassals and later aided the Spartans.', 'A polity defeated by the Greeks in the fifth century BC.', 'A major empire opposed by the Greek cities of Asia in their revolt.', "Empire described in Herodotus's Histories, involved in the Persian Wars.", 'A people whose administrative structures were inherited by Alexander and then the Seleucids.', 'The Persian Empire, ruled by Darius III, opposed and defeated by Alexander.', 'The people and empire Alexander aimed to defeat.', 'An empire whose legacy was inherited by Macedon.', 'A major empire under Macedonian leadership.', 'The empire experiencing decline and internal weaknesses during the fourth century.', 'The empire targeted by Alexander for conquest starting in 334 BC.', 'Empire against which the Hellenic crusade was directed.', 'Empire where Alexander proclaimed himself heir to the Great King.', 'A major empire in the Middle East that stimulated economic life but also caused inflation and instability.', 'The preceding empire from which the Seleucid kings inherited the theory of absolutism and their system of taxation.'], occurrence_count=24, book_indices=[3], source_book_chapters=['3:2', '3:3'], source_pages=[256, 265, 266, 267, 268, 269, 271, 272, 279, 289, 297, 300, 301, 302, 305, 307, 308, 312], source_paragraph_ids=['34b77195-ff73-4135-943a-16bdd32b7c6b', '9570d9c2-572e-43db-870a-2ecaa0324acc', 'aa1f82c6-7003-4e97-97e1-aaab1be45bc2', '55af6a7d-327d-40d8-b0d5-703d36919593', '2c21c9fc-6685-4098-941c-056c46ff264b', '60c53ad9-9b7a-4208-8486-0715fe11eeb4', 'ad04e84f-8cc1-4bd7-ac73-a07d11281ea0', '9e6baedf-5245-4429-9884-ed105da26c77', '01f84f6a-0902-49f7-ab19-fa9343e44aed', '882f7bb9-6372-440a-be3d-88dc0d6419e9', '18a45d94-6bba-4479-99ac-ea635b3ff900', '314d43f9-93b5-4390-aa90-c40dc248d595', 'be445098-58aa-41af-a8a5-74296270af64', 'c10eb7d6-3c79-469d-8ed2-5247e8b41e8b', '3929aa33-5c57-4996-89cd-5dea80483868', '388df28c-9cd4-40f4-b8d9-f95cae0cf63c', '0223ff2b-2e51-4545-b03b-b0a5a32f8466', 'c3e9fd8a-59c5-4cd9-82fe-d36d56c5a4b9', '61f64f00-9c16-411a-87d7-73d2b9a96754', '013bf0e4-6276-495f-a598-1fc873c48400', '2c0e4077-6349-45fb-a397-3534ddd5e30d', 'cd1acf18-83d8-404a-8c1f-8c5e27d3b9e9', '2eec895a-d0c2-4490-bcd2-8a0279517d96', '7daf9b92-2cec-4692-a6bc-808e22720107'], merged_from_count=24),
  0.4174959659576416),
 (KGEntity(id='954f1df6-ab33-43f8-aae5-655612b6b571', graph_name='book3_ch2-3', name='Darius III', entity_type='person', aliases=[], descriptions=['Persian king defeated by Alexander at Gaugamela and murdered by one of his satraps.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[301], source_paragraph_ids=['0223ff2b-2e51-4545-b03b-b0a5a32f8466'], merged_from_count=1),
  0.4136846661567688),
 (KGEntity(id='a5f03692-33a1-4a45-823e-4546e4f54eec', graph_name='book3_ch2-3', name='Eretria', entity_type='polity', aliases=[], descriptions=['A Greek city-state that sent a fleet to support the Ionian revolt against Persia.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:2'], source_pages=[266], source_paragraph_ids=['61f64f00-9c16-411a-87d7-73d2b9a96754'], merged_from_count=1),
  0.4113498330116272),
 (KGEntity(id='75be6ff4-f7e5-4dec-a529-334a44e91240', graph_name='book3_ch2-3', name='Phocis', entity_type='polity', aliases=[], descriptions=['A polity crushed in a war involving Athens and Macedon.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[299], source_paragraph_ids=['75726c0d-3980-46cf-a09d-fd7b01596cf2'], merged_from_count=1),
  0.4078872799873352),
 (KGEntity(id='e2db75a3-5d7a-49cc-8f6b-589cfe519108', graph_name='book3_ch2-3', name='India', entity_type='place', aliases=[], descriptions=['A region to which classical Greek architecture spread.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:2'], source_pages=[293], source_paragraph_ids=['a1504d22-bfab-478f-b3f8-55eaad11d67a'], merged_from_count=1),
  0.40447890758514404),
 (KGEntity(id='39180361-df42-4493-b435-a5c246d483ea', graph_name='book3_ch2-3', name='Stateira (Daughter of Darius III)', entity_type='person', aliases=['Persian princess'], descriptions=['Daughter of Darius, married by Alexander as part of cultural integration.', 'Second wife of Alexander, symbolizing integration with Persian elites.'], occurrence_count=2, book_indices=[3], source_book_chapters=['3:3'], source_pages=[302], source_paragraph_ids=['be445098-58aa-41af-a8a5-74296270af64', '2975d6e7-a940-40fc-b553-430fa8ae689e'], merged_from_count=2),
  0.40334928035736084),
 (KGEntity(id='30e6b047-205a-4858-ab28-03b1dec263e5', graph_name='book3_ch2-3', name='Celts', entity_type='polity', aliases=[], descriptions=['Migrating people from northern Europe who invaded Macedonia and disrupted the Seleucid Empire.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[306], source_paragraph_ids=['c899da96-aba2-492f-8977-02dabaa18fd9'], merged_from_count=1),
  0.40210485458374023),
 (KGEntity(id='8cc932b2-486a-45b4-b2da-2bcd7dc9dadf', graph_name='book3_ch2-3', name='Greece', entity_type='polity', aliases=[], descriptions=["A collection of city-states that provided a quarter of Alexander's army and were initially difficult for him to control."], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[300], source_paragraph_ids=['3929aa33-5c57-4996-89cd-5dea80483868'], merged_from_count=1),
  0.4004707336425781),
 (KGEntity(id='3fb95b4c-a5a0-42fd-a7bb-6b5b5da60d5d', graph_name='book3_ch2-3', name='Attalids', entity_type='person', aliases=['Attalid dynasty'], descriptions=['The ruling dynasty of the Kingdom of Pergamon who pushed the Celts further into Asia Minor.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[306], source_paragraph_ids=['c899da96-aba2-492f-8977-02dabaa18fd9'], merged_from_count=1),
  0.39533448219299316),
 (KGEntity(id='040d35a2-718a-4620-95f9-89ea23565a29', graph_name='book3_ch2-3', name='Lydia', entity_type='polity', aliases=[], descriptions=['People of Lydia, who had conflicts with Greek cities of Asia Minor.', 'The first to strike true coins, influencing trade in the sixth century BC.', 'A kingdom in Asia, ruled by Croesus, that was Hellenized by its tributary Greek cities and adopted art and alphabet influences.', 'Kingdom ruled by Croesus, undergoing Hellenization.', 'A kingdom overthrown by Persia around 540 BC, ending the reign of Croesus.'], occurrence_count=5, book_indices=[3], source_book_chapters=['3:2'], source_pages=[257, 265, 266], source_paragraph_ids=['61f64f00-9c16-411a-87d7-73d2b9a96754', 'aa1f82c6-7003-4e97-97e1-aaab1be45bc2', '51d38599-31a6-4d36-87c6-f47a7289fd30', 'ab3b0165-9408-463f-92fa-f2658486f1f2'], merged_from_count=5),
  0.39284253120422363),
 (KGEntity(id='9c73c18d-4028-4cf8-9cad-b190c97c8169', graph_name='book3_ch2-3', name='Hellespont', entity_type='place', aliases=[], descriptions=['Location to which the Persian king retreated after the naval defeat'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:2'], source_pages=[268], source_paragraph_ids=['b4331f08-be16-46bd-afab-42508adb7b8b'], merged_from_count=1),
  0.38797664642333984),
 (KGEntity(id='8d67acca-c259-4cbf-ac31-460f6556e0fd', graph_name='book3_ch2-3', name='Persian army', entity_type='polity', aliases=['Asian armies'], descriptions=['Military force of the Persians invading Greece', 'Armies from Asia that were opposed by Greek forces in battle.'], occurrence_count=2, book_indices=[3], source_book_chapters=['3:2'], source_pages=[258, 267], source_paragraph_ids=['388df28c-9cd4-40f4-b8d9-f95cae0cf63c', '8e60f63d-f7e9-4c2d-9baa-ad97c6d8022d'], merged_from_count=2),
  0.3875623345375061),
 (KGEntity(id='a7748398-25f8-4cfa-b399-3f50dd92fe27', graph_name='book3_ch2-3', name='Antioch', entity_type='place', aliases=[], descriptions=['The capital city of the Seleucid Empire located in Syria.'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[306], source_paragraph_ids=['c899da96-aba2-492f-8977-02dabaa18fd9'], merged_from_count=1),
  0.38616716861724854),

In [7]:
test_rel = mgr.kg_relationships.find_by_criteria(criteria={"graph_name": graph_name, "relation_type": "influenced"}, limit=1)[0]

In [8]:
test_rel.__dict__

{'id': 'dfdc7770-9c12-47a3-83fe-d9abe2314c12',
 'graph_name': 'book3_ch2-3',
 'source_entity_id': '36f27116-2092-4d75-9074-b915a6f1561a',
 'target_entity_id': 'a8c0a709-5739-432a-a28a-54e434453d60',
 'entity_ids': ['36f27116-2092-4d75-9074-b915a6f1561a',
  'a8c0a709-5739-432a-a28a-54e434453d60'],
 'source_entity_name': 'Greece',
 'target_entity_name': 'Italy',
 'relation_type': 'influenced',
 'description': 'Greek products have been found in Italy, indicating influence through commerce.',
 'temporal_context': 'sixth century',
 'start_year': -600.0,
 'end_year': -501.0,
 'temporal_precision': 'century',
 'paragraph_id': '196d4aa2-160c-45d2-bf05-6c08f4dafc54',
 'book_index': 3,
 'chapter_index': 2,
 'page': 265}

# Check description source paragraphs

In [3]:
from history_book.database.config.database_config import WeaviateConfig
from history_book.database.repositories.book_repository import BookRepositoryManager

config = WeaviateConfig.from_environment()
mgr = BookRepositoryManager(config)

# Quick counts
print(f"KG Entities:       {mgr.kg_entities.count()}")
print(f"KG Relationships:  {mgr.kg_relationships.count()}")
print(f"KG Graphs:         {mgr.kg_graphs.count()}")

# What graphs do we have?
for g in mgr.kg_graphs.list_all():
    print(f"\n  {g.name} ({g.graph_type}): {g.entity_count} entities, {g.relationship_count} rels, chapters={g.book_chapters}")

KG Entities:       267
KG Relationships:  466
KG Graphs:         1

  book3_ch2-3 (book): 267 entities, 466 rels, chapters=['3:2', '3:3']

In [4]:
# Which graph has this paragraph? Use the merged book graph.
graph_name = "book3_ch2-3"

In [5]:
top_entities = mgr.kg_entities.find_by_criteria(criteria={"graph_name": graph_name}, sort_by="occurrence_count", ascending=False, limit=10)

In [6]:
for entity in top_entities:
    print(f"{entity.name} ({entity.entity_type}) — occurrences: {entity.occurrence_count}, aliases: {entity.aliases}")

Greece (polity) — occurrences: 32, aliases: ['Greek literature', 'Greek world', 'Greek thought', 'classical Greece', 'archaic Greece', 'Hellenes', 'Greek states', 'Greeks', 'ancient Greece', 'Greek']
Athens (polity) — occurrences: 29, aliases: ['Athenians']
Achaemenid Empire (polity) — occurrences: 22, aliases: ['Persia', 'Persian rule', 'Persian power', 'Achaemenids', 'that empire']
Alexander the Great (person) — occurrences: 15, aliases: ['Alexander', 'the Great']
Sparta (polity) — occurrences: 15, aliases: ['Spartan', 'Spartan League', 'Spartans']
Hellenistic culture (concept) — occurrences: 13, aliases: ['Hellenistic world', 'Hellenistic (Greek) civilization', 'Greek culture', 'Greek states', 'Hellenism', 'classical civilization']
Greece (place) — occurrences: 12, aliases: ['ancient Greece', 'Greek peninsula', 'Greek world']
Athens (place) — occurrences: 10, aliases: ['fifth-century Athens', 'Athens in the fifth century']
Macedon (polity) — occurrences: 9, aliases: ['Macedonian Empire', 'Macedonia']
Plato (person) — occurrences: 9, aliases: []

In [7]:
ent_hellen = top_entities[5]
ent_hellen.__dict__

{'id': '33f19269-7cfe-4ef8-8207-683d64cb704b',
 'graph_name': 'book3_ch2-3',
 'name': 'Hellenistic culture',
 'entity_type': 'concept',
 'aliases': ['Hellenistic world',
  'Hellenistic (Greek) civilization',
  'Greek culture',
  'Greek states',
  'Hellenism',
  'classical civilization'],
 'descriptions': ['An idea created by later ages to represent the cultural and intellectual achievements of the Greeks, especially in the fifth century BC.',
  'The name given by the Romans centuries later to the Greek-speaking peoples.',
  'The civilization that emerged in the Aegean region influenced by earlier Minoan and Mycenaean cultures.',
  'The cultural and historical achievements of the Greeks during their greatest age.',
  'A civilization consisting of many Greek states scattered over the Aegean region.',
  'A civilization noted for its early vigorous and perceptive ideas about nature, exemplified by the Ionians.',
  'A cultural period characterized by eclecticism and cosmopolitanism, blending Greek and Eastern elements.',
  'Civilization preserving Greek tradition in science during Hellenistic times.',
  'A civilization richer than its predecessors, marked by population growth.',
  'Cultural and political world organized by Macedon characterized by Greek inspiration and language.',
  "Cultural world that emerged after the collapse of Alexander's empire.",
  'The civilization that extended greatly during the peaceful setting provided by the Hellenistic kingdoms.',
  'The culture of the Greeks during the Hellenistic period, which experienced a deceptive triumph.'],
 'description_paragraph_ids': ['882f7bb9-6372-440a-be3d-88dc0d6419e9',
  'a2054151-ca19-4034-8b98-b0f02086e757',
  'ddf635ec-68eb-4fa6-ae67-a0ba76708403',
  'c3e9fd8a-59c5-4cd9-82fe-d36d56c5a4b9',
  '0f74c00a-a4cd-46f9-ab09-867adac2fa74',
  '5c25e478-f7d1-446c-8a77-65775a6d29c9',
  '0de915c4-7598-4c9e-b090-7ed94867fe1f',
  '5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d',
  '314d43f9-93b5-4390-aa90-c40dc248d595',
  'cd1acf18-83d8-404a-8c1f-8c5e27d3b9e9',
  '45bdfa38-4ab1-4a96-9092-d9eb5151c145',
  'ecd591b3-d60d-4353-b814-e221c48df921',
  '69cd812d-e025-410e-aea2-a4bb161bf4db'],
 'occurrence_count': 13,
 'book_indices': [3],
 'source_book_chapters': ['3:2', '3:3'],
 'source_pages': [250, 268, 272, 284, 297, 305, 306, 308, 309, 310, 312],
 'source_paragraph_ids': ['5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d',
  'cd1acf18-83d8-404a-8c1f-8c5e27d3b9e9',
  '5c25e478-f7d1-446c-8a77-65775a6d29c9',
  'ddf635ec-68eb-4fa6-ae67-a0ba76708403',
  'a2054151-ca19-4034-8b98-b0f02086e757',
  '882f7bb9-6372-440a-be3d-88dc0d6419e9',
  '314d43f9-93b5-4390-aa90-c40dc248d595',
  'ecd591b3-d60d-4353-b814-e221c48df921',
  '45bdfa38-4ab1-4a96-9092-d9eb5151c145',
  '0f74c00a-a4cd-46f9-ab09-867adac2fa74',
  'c3e9fd8a-59c5-4cd9-82fe-d36d56c5a4b9',
  '69cd812d-e025-410e-aea2-a4bb161bf4db',
  '0de915c4-7598-4c9e-b090-7ed94867fe1f'],
 'merged_from_count': 13}

In [8]:
ent_hellen.descriptions[7]

'Civilization preserving Greek tradition in science during Hellenistic times.'

In [9]:
ent_hellen.description_paragraph_ids[7]

'5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d'

In [11]:
para = mgr.paragraphs.get_by_id(ent_hellen.description_paragraph_ids[7])

In [15]:
print_with_wrapping(para.text)

Hellenistic civilization preserved the Greek tradition most successfully in
science, and here Alexandria, the greatest of all Hellenistic cities, was pre-
eminent. Euclid was the greatest systematizer of geometry, defining it until the
nineteenth century, and Archimedes, famous for his practical achievements in the
construction of war-machines in Sicily, was probably Euclid’s pupil. Another
Alexandrian, Eratosthenes, was the first man to measure the size of the earth,
and a Hellenistic Greek, Aristarchus of Samos, got so far as to say that the
earth moved around the sun, though his views were set aside by contemporaries
and posterity because they could not be squared with Aristotelian physics which
stated the contrary. In hydrostatics, Archimedes made great strides (and
invented the windlass, too), but the central achievement of the Greek tradition
was always mathematical, not practical, and in Hellenistic times it reached its
apogee with the theory of conic sections and ellipses and the founding of
trigonometry.

In [16]:
mgr.kg_entities.find_by_paragraph(para.id, graph_name)

[KGEntity(id='a259b46e-d9e8-4722-8a62-12b3edeae8f4', graph_name='book3_ch2-3', name='Alexandria', entity_type='place', aliases=[], descriptions=['City in Egypt where Ptolemy conducted his astronomical work.', 'City with one of the two greatest libraries of the ancient world.', 'The greatest of all Hellenistic cities, pre-eminent in science.'], description_paragraph_ids=['a4a41817-b296-4985-b034-64839febfa1c', 'f39c7c88-f6e3-4e6a-9aa9-64a902236163', '5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d'], occurrence_count=3, book_indices=[3], source_book_chapters=['3:2', '3:3'], source_pages=[285, 308, 309], source_paragraph_ids=['f39c7c88-f6e3-4e6a-9aa9-64a902236163', 'a4a41817-b296-4985-b034-64839febfa1c', '5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d'], merged_from_count=3),
 KGEntity(id='33f19269-7cfe-4ef8-8207-683d64cb704b', graph_name='book3_ch2-3', name='Hellenistic culture', entity_type='concept', aliases=['Hellenistic world', 'Hellenistic (Greek) civilization', 'Greek culture', 'Greek states', 'Hellenism', 'classical civilization'], descriptions=['An idea created by later ages to represent the cultural and intellectual achievements of the Greeks, especially in the fifth century BC.', 'The name given by the Romans centuries later to the Greek-speaking peoples.', 'The civilization that emerged in the Aegean region influenced by earlier Minoan and Mycenaean cultures.', 'The cultural and historical achievements of the Greeks during their greatest age.', 'A civilization consisting of many Greek states scattered over the Aegean region.', 'A civilization noted for its early vigorous and perceptive ideas about nature, exemplified by the Ionians.', 'A cultural period characterized by eclecticism and cosmopolitanism, blending Greek and Eastern elements.', 'Civilization preserving Greek tradition in science during Hellenistic times.', 'A civilization richer than its predecessors, marked by population growth.', 'Cultural and political world organized by Macedon characterized by Greek inspiration and language.', "Cultural world that emerged after the collapse of Alexander's empire.", 'The civilization that extended greatly during the peaceful setting provided by the Hellenistic kingdoms.', 'The culture of the Greeks during the Hellenistic period, which experienced a deceptive triumph.'], description_paragraph_ids=['882f7bb9-6372-440a-be3d-88dc0d6419e9', 'a2054151-ca19-4034-8b98-b0f02086e757', 'ddf635ec-68eb-4fa6-ae67-a0ba76708403', 'c3e9fd8a-59c5-4cd9-82fe-d36d56c5a4b9', '0f74c00a-a4cd-46f9-ab09-867adac2fa74', '5c25e478-f7d1-446c-8a77-65775a6d29c9', '0de915c4-7598-4c9e-b090-7ed94867fe1f', '5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d', '314d43f9-93b5-4390-aa90-c40dc248d595', 'cd1acf18-83d8-404a-8c1f-8c5e27d3b9e9', '45bdfa38-4ab1-4a96-9092-d9eb5151c145', 'ecd591b3-d60d-4353-b814-e221c48df921', '69cd812d-e025-410e-aea2-a4bb161bf4db'], occurrence_count=13, book_indices=[3], source_book_chapters=['3:2', '3:3'], source_pages=[250, 268, 272, 284, 297, 305, 306, 308, 309, 310, 312], source_paragraph_ids=['5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d', 'cd1acf18-83d8-404a-8c1f-8c5e27d3b9e9', '5c25e478-f7d1-446c-8a77-65775a6d29c9', 'ddf635ec-68eb-4fa6-ae67-a0ba76708403', 'a2054151-ca19-4034-8b98-b0f02086e757', '882f7bb9-6372-440a-be3d-88dc0d6419e9', '314d43f9-93b5-4390-aa90-c40dc248d595', 'ecd591b3-d60d-4353-b814-e221c48df921', '45bdfa38-4ab1-4a96-9092-d9eb5151c145', '0f74c00a-a4cd-46f9-ab09-867adac2fa74', 'c3e9fd8a-59c5-4cd9-82fe-d36d56c5a4b9', '69cd812d-e025-410e-aea2-a4bb161bf4db', '0de915c4-7598-4c9e-b090-7ed94867fe1f'], merged_from_count=13),
 KGEntity(id='a88c3d6d-776a-481d-b88d-d6c6e1306081', graph_name='book3_ch2-3', name='Euclid', entity_type='person', aliases=[], descriptions=['Greatest systematizer of geometry, defining it until the nineteenth century.'], description_paragraph_ids=['5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[309], source_paragraph_ids=['5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d'], merged_from_count=1),
 KGEntity(id='fe3d9042-1f16-440e-81d1-bc7cb5abe641', graph_name='book3_ch2-3', name='Archimedes', entity_type='person', aliases=[], descriptions=['Famous for practical achievements in war-machines in Sicily and contributions to hydrostatics.'], description_paragraph_ids=['5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d'], occurrence_count=1, book_indices=[3], source_book_chapters=['3:3'], source_pages=[309], source_paragraph_ids=['5ef9ce6b-d820-46c7-90bc-1b7d9d7d945d'], merged_from_count=1)]

# Merge auditing

In [4]:
mgr.kg_merge_decisions.count()

1873

In [5]:
graph_name = "book3_ch4_5"

In [6]:
all_merges = mgr.kg_merge_decisions.list_all()

In [7]:
all_merges

[KGMergeDecision(id='00078226-ff33-46ce-828f-3cfcc475ac65', graph_name='book3_ch4', merge_type='root', entity1_name='New Carthage', entity1_type='place', entity1_aliases=['Cartagena'], entity1_source_graph='', entity2_name='New Carthage', entity2_type='place', entity2_aliases=[], canonical_name='New Carthage', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 665001, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0011c40d-c641-4ffc-b2e8-824f1bbb2a53', graph_name='book3_ch4_5', merge_type='root', entity1_name='barbarian warlords', entity1_type='person', entity1_aliases=[], entity1_source_graph='book3_ch5', entity2_name='barbarian warlords', entity2_type='person', entity2_aliases=[], canonical_name='barbarian warlords', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 51, 789373, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0028838c-3398-42e6-a8d2-5d6a3f91a324', graph_name='book3_ch5', merge_type='llm', entity1_name='Roman Empire', entity1_type='polity', entity1_aliases=['Empire', 'Roman administration', 'classical world', 'late Roman empire', 'old empire', 'Byzantine Empire', 'Rome', 'empire', 'Roman government', 'Romans', 'Roman authorities'], entity1_source_graph='', entity2_name='Roman Empire', entity2_type='polity', entity2_aliases=['classical world', 'Roman administration', 'Empire', 'late Roman empire', 'old empire', 'Byzantine Empire', 'Rome', 'empire', 'Roman government', 'Romans', 'Roman authorities'], canonical_name='Roman Empire', similarity=0.6934427485602068, reasoning='Entity 1 labeled simply as "Roman" with description describing pagan traditions layered beneath Germanic and above Celtic beliefs refers to the Roman polity/civilization influencing barbarian peoples. Entity 2 is clearly the Roman Empire with extensive aliases including "Rome", "old empire", "Byzantine Empire" and descriptions matching influence on barbarians and Christianity. These are the same political entity (the Roman polity/empire) and should be merged. Canonical name chosen: Roman Empire (most specific and widely used).', occurrence_count_after=45, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 624442, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='00373725-6f39-4652-935b-f1f60f35bc90', graph_name='book3_ch4', merge_type='root', entity1_name='Rome', entity1_type='polity', entity1_aliases=[], entity1_source_graph='', entity2_name='Rome', entity2_type='polity', entity2_aliases=[], canonical_name='Rome', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 661502, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='00482f2e-d7fb-4729-b606-17708a834509', graph_name='book3_ch4', merge_type='root', entity1_name='Plebs', entity1_type='concept', entity1_aliases=[], entity1_source_graph='', entity2_name='Plebs', entity2_type='concept', entity2_aliases=[], canonical_name='Plebs', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 663209, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='006e972e-5fbc-403a-8771-2224b0ed2a35', graph_name='book3_ch4', merge_type='rule', entity1_name='Trajan', entity1_type='person', entity1_aliases=[], entity1_source_graph='', entity2_name='Trajan', entity2_type='person', entity2_aliases=[], canonical_name='Trajan', similarity=None, reasoning='', occurrence_count_after=3, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 671309, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='007bc8bb-2a15-4133-b9a0-832a75fb3ceb', graph_name='book3_ch4', merge_type='llm', entity1_name='Rome', entity1_type='polity', entity1_aliases=['republic', 'empire', 'Roman Republic', 'early republic', 'The republic', 'Rome (Roman state)'], entity1_source_graph='', entity2_name='Roman Republic', entity2_type='polity', entity2_aliases=['republic', 'empire', 'early republic', 'The republic', 'Rome (Roman state)'], canonical_name='Rome (Roman state)', similarity=0.7568930197919009, reasoning="Entity 1 refers to the city/capital 'Rome'. Entity 2 refers broadly to the Roman state/polity (Roman Republic and its continuation into empire). The user-provided guidance gives an example where 'Roman Republic' and 'Rome' (Roman state) are mergeable. Here Entity 1 is labeled polity but description is the capital; Entity 2 is the Roman polity. They refer to the same overarching political entity (Rome as the Roman state). Therefore they should be merged, with the canonical name being the broader, commonly used polity name 'Roman Republic' or simply 'Rome'. 'Rome' is the most general/common name for the polity in many contexts, but given Entity 2's focus on the polity, canonical name chosen as 'Rome (Roman state)'.", occurrence_count_after=47, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 672698, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='007bd3b9-b2cf-4f0d-9b85-8672c16dd896', graph_name='book3_ch4', merge_type='llm', entity1_name='Rome', entity1_type='polity', entity1_aliases=['Roman Republic', 'Roman culture', 'republic', 'empire', 'early republic', 'The republic', 'Rome (Roman state)'], entity1_source_graph='', entity2_name='Rome', entity2_type='polity', entity2_aliases=['republic', 'empire', 'Roman Republic', 'early republic', 'The republic', 'Rome (Roman state)'], canonical_name='Rome', similarity=0.655521501800089, reasoning='Both refer to the same broad Roman polity/civilization. Entity 2 (Rome) is an extensive description of the Roman state across republican and imperial phases; Entity 1 (Roman civilization) is a label for that civilization/culture. They are not distinct historical entities but two names for the same Roman polity/civilization and should be merged. Canonical name chosen: Rome (covers city, state, republic, empire and common usage).', occurrence_count_after=48, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 673128, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='007f33e3-0ba4-4ee1-89bb-c91dce5b9053', graph_name='book3_ch5', merge_type='root', entity1_name='Crimean Goths', entity1_type='polity', entity1_aliases=[], entity1_source_graph='', entity2_name='Crimean Goths', entity2_type='polity', entity2_aliases=[], canonical_name='Crimean Goths', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 622336, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='00bdfb87-3b91-4b7b-ba96-ea6fa3e076dc', graph_name='book3_ch5', merge_type='root', entity1_name='Merovingian princes', entity1_type='person', entity1_aliases=[], entity1_source_graph='', entity2_name='Merovingian princes', entity2_type='person', entity2_aliases=[], canonical_name='Merovingian princes', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 621303, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='011efb96-263b-463b-bc8f-006f646747ea', graph_name='book3_ch4', merge_type='llm', entity1_name='Rome', entity1_type='polity', entity1_aliases=['republic', 'empire', 'Roman Republic', 'early republic'], entity1_source_graph='', entity2_name='Roman Republic', entity2_type='polity', entity2_aliases=['republic', 'early republic', 'empire'], canonical_name='Roman Republic', similarity=0.7568202688113645, reasoning="Both mentions refer to the same political entity: Rome as the polity in its republican phase (the Roman Republic). Descriptions align on Hellenization, conquest of Carthage, Punic Wars, and institutions like SPQR. Although one label is broader ('Rome'), the context matches the Roman Republic rather than a distinct later empire, so they should be merged under the common name 'Roman Republic'.", occurrence_count_after=27, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 667021, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='012fcd79-004d-42c5-93d6-9208ec56e5a8', graph_name='book3_ch4_5', merge_type='root', entity1_name='emperor', entity1_type='concept', entity1_aliases=[], entity1_source_graph='book3_ch5', entity2_name='emperor', entity2_type='concept', entity2_aliases=[], canonical_name='emperor', similarity=None, reasoning='', occurrence_count_after=2, created_at=datetime.datetime(2026, 3, 15, 20, 40, 51, 787718, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='013e4fc4-002f-49e8-baa6-bd0b412e3191', graph_name='book3_ch5', merge_type='root', entity1_name='Greeks', entity1_type='polity', entity1_aliases=[], entity1_source_graph='', entity2_name='Greeks', entity2_type='polity', entity2_aliases=[], canonical_name='Greeks', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 619941, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='016430e9-0fee-4513-bef5-6d82f34a9aed', graph_name='book3_ch5', merge_type='rule', entity1_name='Constantine', entity1_type='person', entity1_aliases=[], entity1_source_graph='', entity2_name='Constantine the Great', entity2_type='person', entity2_aliases=['Constantine'], canonical_name='Constantine the Great', similarity=None, reasoning='', occurrence_count_after=12, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 618484, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0168ea6f-c8c8-43ec-b326-a5309633960c', graph_name='book3_ch5', merge_type='root', entity1_name='Severus', entity1_type='person', entity1_aliases=[], entity1_source_graph='', entity2_name='Severus', entity2_type='person', entity2_aliases=[], canonical_name='Severus', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 616336, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='01ffb2be-2eae-4c22-bacb-791efdeadc7d', graph_name='book3_ch5', merge_type='root', entity1_name='Simon Bar Kochba', entity1_type='person', entity1_aliases=['last ‘Messiah’'], entity1_source_graph='', entity2_name='Simon Bar Kochba', entity2_type='person', entity2_aliases=[], canonical_name='Simon Bar Kochba', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 615463, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0248b57e-cec9-4aa3-a350-e3f4d5925e59', graph_name='book3_ch5', merge_type='rule', entity1_name='Spain', entity1_type='place', entity1_aliases=[], entity1_source_graph='', entity2_name='Spain', entity2_type='place', entity2_aliases=[], canonical_name='Spain', similarity=None, reasoning='', occurrence_count_after=4, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 621802, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='026707b3-3515-4c58-92f0-b62a7039bd84', graph_name='book3_ch5', merge_type='llm', entity1_name='Roman paganism', entity1_type='concept', entity1_aliases=['paganism', 'Roman tradition'], entity1_source_graph='', entity2_name='Roman tradition', entity2_type='concept', entity2_aliases=[], canonical_name='Roman paganism', similarity=0.7010077357105897, reasoning='Both entries describe the same general concept: the traditional Roman religious system and practices (pagan beliefs and sacrificial traditions). They are not distinct entities but two phrasings of Roman traditional religion, so they should be merged.', occurrence_count_after=2, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 619763, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='02702279-a906-4861-8441-fe1b1d279209', graph_name='book3_ch5', merge_type='llm', entity1_name='Augustine of Hippo', entity1_type='person', entity1_aliases=['St Augustine', 'St Augustine (Augustine of Hippo)'], entity1_source_graph='', entity2_name='Augustine of Hippo', entity2_type='person', entity2_aliases=['St Augustine', 'St Augustine (Augustine of Hippo)'], canonical_name='Augustine of Hippo', similarity=0.8232442972729966, reasoning='Both descriptions clearly refer to the same individual: Augustine of Hippo, major Church Father who opposed Donatists and Pelagians, bishop of Hippo, born in Africa in 354. Names are variant forms of the same person.', occurrence_count_after=5, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 620445, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='027540d7-8605-4ef4-8957-297d24b0b97c', graph_name='book3_ch5', merge_type='root', entity1_name='Attila', entity1_type='person', entity1_aliases=[], entity1_source_graph='', entity2_name='Attila', entity2_type='person', entity2_aliases=[], canonical_name='Attila', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 619357, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='02ac1600-21da-44ec-a7b6-464a500f5c25', graph_name='book3_ch5', merge_type='root', entity1_name="Hadrian's Wall", entity1_type='place', entity1_aliases=[], entity1_source_graph='', entity2_name="Hadrian's Wall", entity2_type='place', entity2_aliases=[], canonical_name="Hadrian's Wall", similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 618552, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='02d8708c-9836-4a19-94c5-92ef4c3b1eb2', graph_name='book3_ch4_5', merge_type='root', entity1_name='Belisarius', entity1_type='person', entity1_aliases=[], entity1_source_graph='book3_ch5', entity2_name='Belisarius', entity2_type='person', entity2_aliases=[], canonical_name='Belisarius', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 51, 790582, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='038b4ef8-1421-4947-99c0-3b1e01930cc2', graph_name='book3_ch4', merge_type='root', entity1_name='Roman empire', entity1_type='polity', entity1_aliases=[], entity1_source_graph='', entity2_name='Roman empire', entity2_type='polity', entity2_aliases=[], canonical_name='Roman empire', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 662214, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='03dd7ab1-dc98-4671-8b57-8297932cf445', graph_name='book3_ch5', merge_type='root', entity1_name='Church Fathers', entity1_type='person', entity1_aliases=[], entity1_source_graph='', entity2_name='Church Fathers', entity2_type='person', entity2_aliases=[], canonical_name='Church Fathers', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 619958, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='03e4dd12-29fe-47a4-bbb0-f065c78f9032', graph_name='book3_ch4', merge_type='root', entity1_name='Twelve Tables', entity1_type='concept', entity1_aliases=[], entity1_source_graph='', entity2_name='Twelve Tables', entity2_type='concept', entity2_aliases=[], canonical_name='Twelve Tables', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 667165, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='03e9a15b-985f-424f-bca1-c62a40643e8e', graph_name='book3_ch4', merge_type='rule', entity1_name='Julius Caesar', entity1_type='person', entity1_aliases=[], entity1_source_graph='', entity2_name='Julius Caesar', entity2_type='person', entity2_aliases=['Caesar'], canonical_name='Julius Caesar', similarity=None, reasoning='', occurrence_count_after=7, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 668584, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='040329cf-6872-47f0-96fa-611890307bb2', graph_name='book3_ch4_5', merge_type='root', entity1_name='last emperor to be proclaimed in Britannia', entity1_type='person', entity1_aliases=[], entity1_source_graph='book3_ch5', entity2_name='last emperor to be proclaimed in Britannia', entity2_type='person', entity2_aliases=[], canonical_name='last emperor to be proclaimed in Britannia', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 51, 789826, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='042c9e0b-c869-4229-9218-b6f77b2e3050', graph_name='book3_ch4', merge_type='root', entity1_name='Roman achievement', entity1_type='concept', entity1_aliases=[], entity1_source_graph='', entity2_name='Roman achievement', entity2_type='concept', entity2_aliases=[], canonical_name='Roman achievement', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 661566, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='042d4e34-a1e7-43a9-895e-9e1f2c947878', graph_name='book3_ch4', merge_type='llm', entity1_name='Roman Republic', entity1_type='polity', entity1_aliases=['republic', 'early republic', 'empire'], entity1_source_graph='', entity2_name='Roman Republic', entity2_type='polity', entity2_aliases=['republic', 'early republic', 'empire'], canonical_name='Roman Republic', similarity=0.8112373306683814, reasoning='Both mentions refer to the same polity: the Roman polity in its republican phase. Entity 1 (Rome) described as a republic influenced by Hellenization before expanding beyond Italy matches the detailed description of the Roman Republic in Entity 2. They are not distinct entities (city vs empire) here but the same republican polity.', occurrence_count_after=26, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 666644, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0463230a-261f-421e-9f7b-c8657ef95f86', graph_name='book3_ch4_5', merge_type='root', entity1_name='Monophysites', entity1_type='polity', entity1_aliases=[], entity1_source_graph='book3_ch5', entity2_name='Monophysites', entity2_type='polity', entity2_aliases=[], canonical_name='Monophysites', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 51, 790873, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='04f2ee0b-4f3d-4c0e-8033-d3c0dfc669b2', graph_name='book3_ch4', merge_type='rule', entity1_name='Roman Empire', entity1_type='polity', entity1_aliases=['Empire'], entity1_source_graph='', entity2_name='Roman Empire', entity2_type='polity', entity2_aliases=['republic', 'Rome', 'imperial Rome', 'early republic'], canonical_name='Roman Empire', similarity=None, reasoning='', occurrence_count_after=15, created_at=datetime.datetime(2026, 3, 15, 20, 29, 47, 670072, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='04fcd903-5655-40ee-a832-895e3852c1e2', graph_name='book3_ch5', merge_type='root', entity1_name='soldiers', entity1_type='polity', entity1_aliases=[], entity1_source_graph='', entity2_name='soldiers', entity2_type='polity', entity2_aliases=[], canonical_name='soldiers', similarity=None, reasoning='', occurrence_count_after=1, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 616532, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0513b5ec-9fe6-4358-80b9-e0506a519a58', graph_name='book3_ch5', merge_type='rule', entity1_name='Ravenna', entity1_type='place', entity1_aliases=[], entity1_source_graph='', entity2_name='Ravenna', entity2_type='place', entity2_aliases=[], canonical_name='Ravenna', similarity=None, reasoning='', occurrence_count_after=3, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 621516, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0517bae6-b6fe-4fc9-a26c-47fb8e7d9bad', graph_name='book3_ch5', merge_type='rule', entity1_name='Arianism', entity1_type='concept', entity1_aliases=[], entity1_source_graph='', entity2_name='Arianism', entity2_type='concept', entity2_aliases=[], canonical_name='Arianism', similarity=None, reasoning='', occurrence_count_after=3, created_at=datetime.datetime(2026, 3, 15, 20, 40, 23, 619977, tzinfo=datetime.timezone.utc)),

In [8]:
all_merges_df = pd.DataFrame([m.__dict__ for m in all_merges])

In [9]:
all_merges_df['merge_type'].value_counts()

merge_type
root    966
rule    568
llm     339
Name: count, dtype: int64

In [24]:
all_merges_df[all_merges_df["canonical_name"]=="Julius Caesar"]

,id,graph_name,merge_type,entity1_name,entity1_type,entity1_aliases,entity1_source_graph,entity2_name,entity2_type,entity2_aliases,canonical_name,similarity,reasoning,occurrence_count_after,created_at
25,03e9a15b-985f-424f-bca1-c62a40643e8e,book3_ch4,rule,Julius Caesar,person,[],,Julius Caesar,person,[Caesar],Julius Caesar,NaN,,7,2026-03-15 20:29:47.668584+00:00
37,0606e63f-9347-4008-b95f-c156108ca699,book3_ch4,rule,Julius Caesar,person,[Caesar],,Julius Caesar,person,[Caesar],Julius Caesar,NaN,,4,2026-03-15 20:29:47.668313+00:00
230,1f8d8504-e45d-4298-9342-ecdfce35a52a,book3_ch4,rule,Caesar,person,[],,Julius Caesar,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Julius Caesar,NaN,,11,2026-03-15 20:29:47.674077+00:00
512,44ec805a-418e-4c8a-89c4-0d5c0e44535c,book3_ch4,rule,Julius Caesar,person,[Julius],,Julius Caesar,person,[Caesar],Julius Caesar,NaN,,8,2026-03-15 20:29:47.668695+00:00
629,549265b6-46a7-4e54-99ff-6bafd2d0164b,book3_ch4,rule,Caesar,person,[],,Julius Caesar,person,[Caesar],Julius Caesar,NaN,,5,2026-03-15 20:29:47.668428+00:00
920,7bd1759a-e37c-4c0b-aa63-908a23da2dd8,book3_ch4,rule,Julius Caesar,person,[Caesar],,Julius Caesar,person,"[Julius, Caesar]",Julius Caesar,NaN,,9,2026-03-15 20:29:47.670053+00:00
1131,981e69fb-2b30-494e-8dec-8d1017baaaca,book3_ch4,rule,Caesar,person,[],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Julius Caesar,NaN,,10,2026-03-15 20:29:47.671465+00:00
1268,ab3743ba-8ecd-4863-91bf-8e72d35be6b1,book3_ch4,rule,Caesar,person,[],,Julius Caesar,person,[Caesar],Julius Caesar,NaN,,2,2026-03-15 20:29:47.668127+00:00
1375,b8ec5614-9607-4c67-b36f-987bfb8ae325,book3_ch4,rule,Julius Caesar,person,[Caesar],,Julius Caesar,person,[Caesar],Julius Caesar,NaN,,6,2026-03-15 20:29:47.668492+00:00
1671,e2e25e48-ae02-4996-b551-73dfac6b47a1,book3_ch4,rule,Caesar,person,[],,Julius Caesar,person,[Caesar],Julius Caesar,NaN,,3,2026-03-15 20:29:47.668250+00:00
1807,f5da0770-e98a-419a-8cfd-eccb0584c7ca,book3_ch4,root,Julius Caesar,person,[Caesar],,Julius Caesar,person,[],Julius Caesar,NaN,,1,2026-03-15 20:29:47.668085+00:00
1826,f7a69ff0-7e5f-4e06-9a23-afbb19686eeb,book3_ch4,rule,Julius Caesar,person,[],,Julius Caesar,person,"[Julius, Caesar]",Julius Caesar,NaN,,10,2026-03-15 20:29:47.670645+00:00

In [ ]:
mgr.kg_entities.count()

1026

In [29]:
mgr.kg_entities.find_by_criteria(criteria={"name": "Julius Caesar", "graph_name": "book3_ch4"}, limit=5)

[KGEntity(id='1f0031f0-6981-49a8-b7dc-16fce5b30707', graph_name='book3_ch4', name='Julius Caesar', entity_type='person', aliases=['Julius', 'Caesar'], descriptions=['Young aristocrat elected consul in 59 BC, commander of the army of Gaul, led campaigns resulting in its conquest.', 'A formidable man who wished to remain in Gaul in command of his army and province, later led his army across the River Rubicon beginning a march to Rome.', "Roman leader who marched to Spain to defeat Pompey's legions, pursued Pompey to Egypt, and defeated opposing Roman armies in Africa and Spain.", 'Roman leader who organized political support, packed the Senate with his men, was voted dictator for life, and introduced the Julian calendar.', 'Roman leader assassinated in the Senate on 15 March 44 BC at the height of his success.', 'Roman leader whose acts were confirmed after his death and was proclaimed a god.', 'Great Roman leader, great-uncle and adoptive predecessor of Octavian.', 'Great dictator whose aristocratic connections, wealth, and military support were inherited by Octavian.', 'Predecessor of Augustus who was deified after death.', 'Roman leader who conducted reconnaissances into Britain and Germany and left Gaul with the Channel and Rhine as frontiers.'], description_paragraph_ids=['3fc54317-72f2-45a2-9f76-8651d65faa18', '3a05c0c0-cb11-4bea-b833-1085410512ac', '2e6ef396-c56b-4a2d-aa0c-8ff6bcf1f7d9', '1ef9dd6f-52bd-4f75-81f9-d3d6b8f53874', 'bedf83eb-0968-46f4-9f55-64670a1b43f3', 'fe11ad11-4913-4f4f-97af-1c9f78d2ee8a', '65479508-47b8-42b2-abc5-d1305bf50275', '9880378f-3632-4b9d-9492-1e7fb368877c', '4326ad18-2d63-497a-a67e-d6b794667b3c', '35b6eae7-5389-4564-8078-dfafd6ebbdf2'], occurrence_count=10, book_indices=[3], source_book_chapters=['3:4'], source_pages=[337, 338, 339, 340, 341, 342, 344], source_paragraph_ids=['9880378f-3632-4b9d-9492-1e7fb368877c', '35b6eae7-5389-4564-8078-dfafd6ebbdf2', '1ef9dd6f-52bd-4f75-81f9-d3d6b8f53874', '3fc54317-72f2-45a2-9f76-8651d65faa18', 'bedf83eb-0968-46f4-9f55-64670a1b43f3', '2e6ef396-c56b-4a2d-aa0c-8ff6bcf1f7d9', '3a05c0c0-cb11-4bea-b833-1085410512ac', 'fe11ad11-4913-4f4f-97af-1c9f78d2ee8a', '65479508-47b8-42b2-abc5-d1305bf50275', '4326ad18-2d63-497a-a67e-d6b794667b3c'], merged_from_count=10),
 KGEntity(id='da74f375-b592-43e5-a52c-0ab7483850b1', graph_name='book3_ch4', name='Julius Caesar', entity_type='person', aliases=['Octavian', 'princeps', 'Caesar Augustus', 'Caesar'], descriptions=["Julius Caesar's great-nephew and adopted heir, creator of the Roman Empire's nature and government.", 'Junior branch descendant of Julius Caesar who inherited wealth and military support and fought against Mark Antony.', 'Roman leader who ended the civil war, became consul, and initiated a republican restoration in 27 BC.', 'Roman leader whose power grew and who held tribunician power and pontifex maximus.', 'Ruler who established a benevolent despotism and regularized provincial administration and army.', 'First Roman emperor who intended to be succeeded by a family member.', 'Founder of the imperial system whose legacy included inherent weaknesses.', "Emperor who expanded the Roman Empire's frontiers into Germany and up to the Danube.", 'Roman leader who obtained the return of the Roman standards taken from Crassus.', "A Roman leader whose soldiers' descendants were settled in new military colonies in Gaul.", 'Roman ruler associated with the imperial cult and taxation.'], description_paragraph_ids=['65479508-47b8-42b2-abc5-d1305bf50275', '9880378f-3632-4b9d-9492-1e7fb368877c', '1fa5555b-bef9-4253-ad61-e2ffca2c5e22', 'd7df982c-299b-4272-a6fd-13c5c25521fa', '4326ad18-2d63-497a-a67e-d6b794667b3c', 'f6dd93ef-23ec-4c2c-926e-457638056001', 'e1ed1a6b-6ba3-40e8-8e99-f825310f0e6f', '35b6eae7-5389-4564-8078-dfafd6ebbdf2', '1cfb6550-4c6e-4c63-a181-7dc7a3a15e46', '4abcb5f2-70c6-4d66-81b8-fd9c2b6f1e17', '3d1743cc-522f-4b2b-a09a-e9cb7f09bb0c'], occurrence_count=11, book_indices=[3], source_book_chapters=['3:4'], source_pages=[340, 341, 342, 343, 344, 346, 357], source_paragraph_ids=['4abcb5f2-70c6-4d66-81b8-fd9c2b6f1e17', '3d1743cc-522f-4b2b-a09a-e9cb7f09bb0c', '1fa5555b-bef9-4253-ad61-e2ffca2c5e22', '9880378f-3632-4b9d-9492-1e7fb368877c', '35b6eae7-5389-4564-8078-dfafd6ebbdf2', '4326ad18-2d63-497a-a67e-d6b794667b3c', '1cfb6550-4c6e-4c63-a181-7dc7a3a15e46', 'd7df982c-299b-4272-a6fd-13c5c25521fa', '65479508-47b8-42b2-abc5-d1305bf50275', 'f6dd93ef-23ec-4c2c-926e-457638056001', 'e1ed1a6b-6ba3-40e8-8e99-f825310f0e6f'], merged_from_count=11),
 KGEntity(id='778fa0b5-dd4c-41a5-8cf2-d235314f160c', graph_name='book3_ch4_5', name='Julius Caesar', entity_type='person', aliases=['Julius', 'Caesar'], descriptions=['Young aristocrat elected consul in 59 BC, commander of the army of Gaul, led campaigns resulting in its conquest.', 'A formidable man who wished to remain in Gaul in command of his army and province, later led his army across the River Rubicon beginning a march to Rome.', "Roman leader who marched to Spain to defeat Pompey's legions, pursued Pompey to Egypt, and defeated opposing Roman armies in Africa and Spain.", 'Roman leader who organized political support, packed the Senate with his men, was voted dictator for life, and introduced the Julian calendar.', 'Roman leader assassinated in the Senate on 15 March 44 BC at the height of his success.', 'Roman leader whose acts were confirmed after his death and was proclaimed a god.', 'Great Roman leader, great-uncle and adoptive predecessor of Octavian.', 'Great dictator whose aristocratic connections, wealth, and military support were inherited by Octavian.', 'Predecessor of Augustus who was deified after death.', 'Roman leader who conducted reconnaissances into Britain and Germany and left Gaul with the Channel and Rhine as frontiers.'], description_paragraph_ids=['3fc54317-72f2-45a2-9f76-8651d65faa18', '3a05c0c0-cb11-4bea-b833-1085410512ac', '2e6ef396-c56b-4a2d-aa0c-8ff6bcf1f7d9', '1ef9dd6f-52bd-4f75-81f9-d3d6b8f53874', 'bedf83eb-0968-46f4-9f55-64670a1b43f3', 'fe11ad11-4913-4f4f-97af-1c9f78d2ee8a', '65479508-47b8-42b2-abc5-d1305bf50275', '9880378f-3632-4b9d-9492-1e7fb368877c', '4326ad18-2d63-497a-a67e-d6b794667b3c', '35b6eae7-5389-4564-8078-dfafd6ebbdf2'], occurrence_count=10, book_indices=[3], source_book_chapters=['3:4'], source_pages=[337, 338, 339, 340, 341, 342, 344], source_paragraph_ids=['9880378f-3632-4b9d-9492-1e7fb368877c', '35b6eae7-5389-4564-8078-dfafd6ebbdf2', '1ef9dd6f-52bd-4f75-81f9-d3d6b8f53874', '3fc54317-72f2-45a2-9f76-8651d65faa18', 'bedf83eb-0968-46f4-9f55-64670a1b43f3', '2e6ef396-c56b-4a2d-aa0c-8ff6bcf1f7d9', '3a05c0c0-cb11-4bea-b833-1085410512ac', 'fe11ad11-4913-4f4f-97af-1c9f78d2ee8a', '65479508-47b8-42b2-abc5-d1305bf50275', '4326ad18-2d63-497a-a67e-d6b794667b3c'], merged_from_count=0),
 KGEntity(id='7ee5df22-1704-44d4-9429-090ae5d14471', graph_name='book3_ch4_5', name='Julius Caesar', entity_type='person', aliases=['Octavian', 'princeps', 'Caesar Augustus', 'Caesar'], descriptions=["Julius Caesar's great-nephew and adopted heir, creator of the Roman Empire's nature and government.", 'Junior branch descendant of Julius Caesar who inherited wealth and military support and fought against Mark Antony.', 'Roman leader who ended the civil war, became consul, and initiated a republican restoration in 27 BC.', 'Roman leader whose power grew and who held tribunician power and pontifex maximus.', 'Ruler who established a benevolent despotism and regularized provincial administration and army.', 'First Roman emperor who intended to be succeeded by a family member.', 'Founder of the imperial system whose legacy included inherent weaknesses.', "Emperor who expanded the Roman Empire's frontiers into Germany and up to the Danube.", 'Roman leader who obtained the return of the Roman standards taken from Crassus.', "A Roman leader whose soldiers' descendants were settled in new military colonies in Gaul.", 'Roman ruler associated with the imperial cult and taxation.'], description_paragraph_ids=['65479508-47b8-42b2-abc5-d1305bf50275', '9880378f-3632-4b9d-9492-1e7fb368877c', '1fa5555b-bef9-4253-ad61-e2ffca2c5e22', 'd7df982c-299b-4272-a6fd-13c5c25521fa', '4326ad18-2d63-497a-a67e-d6b794667b3c', 'f6dd93ef-23ec-4c2c-926e-457638056001', 'e1ed1a6b-6ba3-40e8-8e99-f825310f0e6f', '35b6eae7-5389-4564-8078-dfafd6ebbdf2', '1cfb6550-4c6e-4c63-a181-7dc7a3a15e46', '4abcb5f2-70c6-4d66-81b8-fd9c2b6f1e17', '3d1743cc-522f-4b2b-a09a-e9cb7f09bb0c'], occurrence_count=11, book_indices=[3], source_book_chapters=['3:4'], source_pages=[340, 341, 342, 343, 344, 346, 357], source_paragraph_ids=['4abcb5f2-70c6-4d66-81b8-fd9c2b6f1e17', '3d1743cc-522f-4b2b-a09a-e9cb7f09bb0c', '1fa5555b-bef9-4253-ad61-e2ffca2c5e22', '9880378f-3632-4b9d-9492-1e7fb368877c', '35b6eae7-5389-4564-8078-dfafd6ebbdf2', '4326ad18-2d63-497a-a67e-d6b794667b3c', '1cfb6550-4c6e-4c63-a181-7dc7a3a15e46', 'd7df982c-299b-4272-a6fd-13c5c25521fa', '65479508-47b8-42b2-abc5-d1305bf50275', 'f6dd93ef-23ec-4c2c-926e-457638056001', 'e1ed1a6b-6ba3-40e8-8e99-f825310f0e6f'], merged_from_count=0)]

In [27]:
check_merges = mgr.kg_merge_decisions.find_by_entity("Julius Caesar", entity_type="person", graph_name="book3_ch4")

In [28]:
len(check_merges)

12

In [30]:
check_merges[0].__dict__

{'id': 'f5da0770-e98a-419a-8cfd-eccb0584c7ca',
 'graph_name': 'book3_ch4',
 'merge_type': 'root',
 'entity1_name': 'Julius Caesar',
 'entity1_type': 'person',
 'entity1_aliases': ['Caesar'],
 'entity1_source_graph': '',
 'entity2_name': 'Julius Caesar',
 'entity2_type': 'person',
 'entity2_aliases': [],
 'canonical_name': 'Julius Caesar',
 'similarity': None,
 'reasoning': '',
 'occurrence_count_after': 1,
 'created_at': datetime.datetime(2026, 3, 15, 20, 29, 47, 668085, tzinfo=datetime.timezone.utc)}

In [31]:
check_merges_df = pd.DataFrame([m.__dict__ for m in check_merges])

In [32]:
check_merges_df

,id,graph_name,merge_type,entity1_name,entity1_type,entity1_aliases,entity1_source_graph,entity2_name,entity2_type,entity2_aliases,canonical_name,similarity,reasoning,occurrence_count_after,created_at
0,f5da0770-e98a-419a-8cfd-eccb0584c7ca,book3_ch4,root,Julius Caesar,person,[Caesar],,Julius Caesar,person,[],Julius Caesar,None,,1,2026-03-15 20:29:47.668085+00:00
1,ab3743ba-8ecd-4863-91bf-8e72d35be6b1,book3_ch4,rule,Caesar,person,[],,Julius Caesar,person,[Caesar],Julius Caesar,None,,2,2026-03-15 20:29:47.668127+00:00
2,e2e25e48-ae02-4996-b551-73dfac6b47a1,book3_ch4,rule,Caesar,person,[],,Julius Caesar,person,[Caesar],Julius Caesar,None,,3,2026-03-15 20:29:47.668250+00:00
3,0606e63f-9347-4008-b95f-c156108ca699,book3_ch4,rule,Julius Caesar,person,[Caesar],,Julius Caesar,person,[Caesar],Julius Caesar,None,,4,2026-03-15 20:29:47.668313+00:00
4,549265b6-46a7-4e54-99ff-6bafd2d0164b,book3_ch4,rule,Caesar,person,[],,Julius Caesar,person,[Caesar],Julius Caesar,None,,5,2026-03-15 20:29:47.668428+00:00
5,b8ec5614-9607-4c67-b36f-987bfb8ae325,book3_ch4,rule,Julius Caesar,person,[Caesar],,Julius Caesar,person,[Caesar],Julius Caesar,None,,6,2026-03-15 20:29:47.668492+00:00
6,03e9a15b-985f-424f-bca1-c62a40643e8e,book3_ch4,rule,Julius Caesar,person,[],,Julius Caesar,person,[Caesar],Julius Caesar,None,,7,2026-03-15 20:29:47.668584+00:00
7,44ec805a-418e-4c8a-89c4-0d5c0e44535c,book3_ch4,rule,Julius Caesar,person,[Julius],,Julius Caesar,person,[Caesar],Julius Caesar,None,,8,2026-03-15 20:29:47.668695+00:00
8,7bd1759a-e37c-4c0b-aa63-908a23da2dd8,book3_ch4,rule,Julius Caesar,person,[Caesar],,Julius Caesar,person,"[Julius, Caesar]",Julius Caesar,None,,9,2026-03-15 20:29:47.670053+00:00
9,f7a69ff0-7e5f-4e06-9a23-afbb19686eeb,book3_ch4,rule,Julius Caesar,person,[],,Julius Caesar,person,"[Julius, Caesar]",Julius Caesar,None,,10,2026-03-15 20:29:47.670645+00:00
10,981e69fb-2b30-494e-8dec-8d1017baaaca,book3_ch4,rule,Caesar,person,[],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Julius Caesar,None,,10,2026-03-15 20:29:47.671465+00:00
11,1f8d8504-e45d-4298-9342-ecdfce35a52a,book3_ch4,rule,Caesar,person,[],,Julius Caesar,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Julius Caesar,None,,11,2026-03-15 20:29:47.674077+00:00

In [33]:
check_merges_2 = mgr.kg_merge_decisions.find_by_entity("Augustus", entity_type="person", graph_name="book3_ch4")

In [34]:
len(check_merges_2)

15

In [35]:
check_merges_2_df = pd.DataFrame([m.__dict__ for m in check_merges_2])

In [38]:
check_merges_2_df.sort_values("occurrence_count_after")

,id,graph_name,merge_type,entity1_name,entity1_type,entity1_aliases,entity1_source_graph,entity2_name,entity2_type,entity2_aliases,canonical_name,similarity,reasoning,occurrence_count_after,created_at
9,a064e59e-1a21-4dbe-8dd5-570f51e1d6f7,book3_ch4,root,Augustus,person,[],,Augustus,person,[],Augustus,None,,1,2026-03-15 20:29:47.671595+00:00
0,1ff68b74-0fe9-4a41-ad35-6c512141ce7c,book3_ch4,rule,Octavian,person,"[Caesar, Augustus]",,Octavian,person,[Caesar Augustus],Augustus,None,,2,2026-03-15 20:29:47.668672+00:00
10,8dec6d1b-fcc1-400b-be8d-6f9633e2a533,book3_ch4,rule,Augustus,person,[],,Augustus,person,[],Augustus,None,,2,2026-03-15 20:29:47.673466+00:00
4,6b0e48b3-6918-4f80-aea3-786b3c9790f1,book3_ch4,rule,Octavian,person,"[Augustus, princeps]",,Augustus,person,"[Octavian, Caesar Augustus, Caesar]",Augustus,None,,3,2026-03-15 20:29:47.669867+00:00
11,1a9bc028-cc44-4fda-9aeb-cee27ee40934,book3_ch4,rule,Augustus,person,[],,Augustus,person,[],Augustus,None,,3,2026-03-15 20:29:47.673610+00:00
1,919c9bf8-9ff1-47ea-9f32-f8db6ce5a5c3,book3_ch4,rule,Augustus,person,[],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Augustus,None,,4,2026-03-15 20:29:47.669947+00:00
12,825897c8-1b23-431e-9ff7-ae55eef6e14f,book3_ch4,rule,Augustus,person,[],,Augustus,person,[],Augustus,None,,4,2026-03-15 20:29:47.674017+00:00
2,ca42cfb5-06db-49db-ab35-ca083af01f1e,book3_ch4,rule,Augustus,person,[Caesar],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Augustus,None,,5,2026-03-15 20:29:47.670037+00:00
13,0ffe2d48-692e-4008-b9f8-5e9e47db1820,book3_ch4,rule,Augustus,person,[],,Augustus,person,[],Augustus,None,,5,2026-03-15 20:29:47.674611+00:00
3,45b563f1-2b56-4511-a0fb-222a973de096,book3_ch4,rule,Augustus,person,[],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Augustus,None,,6,2026-03-15 20:29:47.670123+00:00
5,6ede5d44-f321-4c23-b402-9a7b4a338b27,book3_ch4,rule,Augustus,person,[],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Augustus,None,,7,2026-03-15 20:29:47.670402+00:00
6,4242177a-6e57-4e49-bf6d-0ceeb767d172,book3_ch4,rule,Augustus,person,[],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Augustus,None,,8,2026-03-15 20:29:47.670628+00:00
14,edb19f60-e2dc-49e5-ac89-d6195163dbe5,book3_ch4_5,rule,Augustus,person,[],book3_ch5,Augustus,person,[],Augustus,None,,8,2026-03-15 20:40:51.784940+00:00
7,3e7ebdda-fae7-45d7-a811-8d5e67615152,book3_ch4,rule,Augustus,person,[],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Augustus,None,,9,2026-03-15 20:29:47.671276+00:00
8,981e69fb-2b30-494e-8dec-8d1017baaaca,book3_ch4,rule,Caesar,person,[],,Augustus,person,"[Octavian, princeps, Caesar Augustus, Caesar]",Julius Caesar,None,,10,2026-03-15 20:29:47.671465+00:00

In [12]:
greece_merges_ch2 = mgr.kg_merge_decisions.find_by_entity_name("Greece",graph_name="book3_ch2")

In [13]:
greece_merges_ch2

[KGMergeDecision(id='82ebd5c4-5b59-4418-9c6f-681841b43562', graph_name='book3_ch2', merge_type='rule', entity1_name='Greece', entity1_type='polity', entity1_aliases=['archaic Greece', 'classical Greece'], entity2_name='Greek world', entity2_type='polity', entity2_aliases=['Greece'], canonical_name='Greece', similarity=None, reasoning='', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 436961, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='ebd376ed-a222-4705-a716-581c432bf03a', graph_name='book3_ch2', merge_type='llm', entity1_name='early Greece', entity1_type='polity', entity1_aliases=[], entity2_name='Greeks', entity2_type='polity', entity2_aliases=['Hellenes'], canonical_name='Greeks (early Greece)', similarity=0.7045108821057713, reasoning="Both mentions refer to the same broad historical entity: the Greeks/early Greek civilization in the archaic period (before and around 500 BC). 'early Greece' describes the society and colonizing phase of the Greeks, while 'Greeks' (Hellenes) is the people themselves; here both clearly point to the same cultural-political group in ancient Greece. They are not distinct entities (one is not a specific subgroup or different polity).", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 437003, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='78808e40-7a3b-485a-85be-bd66468a9312', graph_name='book3_ch2', merge_type='llm', entity1_name='Greeks (early Greece)', entity1_type='polity', entity1_aliases=['Greeks', 'Hellenes'], entity2_name='Greeks', entity2_type='polity', entity2_aliases=['Hellenes'], canonical_name='Greeks', similarity=0.6704765041945976, reasoning="Both mentions refer to the same broad historical group: the ancient Greeks / early Greek society. 'early Greece' describes the formative, pre-500 BC phase of the same people described as 'Greeks' (Hellenes). They are not distinct entities like a polity vs people; both are the Greek polity/people in early antiquity and should be merged under the common term 'Greeks'.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 437023, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='124fbe01-a7a6-475f-b5b9-d1ee4144c762', graph_name='book3_ch2', merge_type='llm', entity1_name='classical Greece', entity1_type='concept', entity1_aliases=['Greeks'], entity2_name='Greeks', entity2_type='concept', entity2_aliases=[], canonical_name='Greeks', similarity=0.7310376083248061, reasoning='Both mentions refer to the same broad concept: the Greek people/culture. "classical Greece" is a later construct describing Greek cultural achievements (esp. 5th c. BC) and "Greeks" is the name Romans used for Greek-speaking peoples; they point to the same historical referent (the Greek people/culture). They are not distinct entities under the task\'s criteria and can be merged. Canonical name chosen as the common ethnonym "Greeks."', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 439528, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='f93f97a7-74cc-4c10-bfd6-1129392a5e55', graph_name='book3_ch2', merge_type='rule', entity1_name='Greeks', entity1_type='polity', entity1_aliases=['Greek'], entity2_name='Greeks (early Greece)', entity2_type='polity', entity2_aliases=['Greeks', 'Hellenes'], canonical_name='Greeks', similarity=None, reasoning='', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 437176, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='758d4d78-c596-4ab1-86e8-7e58f53d8b83', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='place', entity1_aliases=[], entity2_name='ancient Greece', entity2_type='place', entity2_aliases=['early Greece'], canonical_name='Ancient Greece', similarity=0.7036001962289724, reasoning='Both mentions refer to the same geographical/cultural entity: Greece in classical/ancient times. The descriptions align (Classical Greece; ancient/early Greece, region of Sparta and Athens). They are not distinct entities or different senses that would prevent merging.', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 439849, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0356049e-dd69-436a-9970-5ab81e30dc42', graph_name='book3_ch2', merge_type='llm', entity1_name='Ancient Greece', entity1_type='place', entity1_aliases=['early Greece'], entity2_name='ancient Greece', entity2_type='place', entity2_aliases=['early Greece'], canonical_name='ancient Greece', similarity=0.6873432998055266, reasoning='Both mentions refer to the same geographical/civilizational entity: classical/ancient Greece (the region and society in early historical times). The descriptions align (Classical Greece delimited by Persian Wars and Macedonian conquests vs ancient/early Greece with Athens and Sparta). They are not distinct entities.', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 439872, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='31d5d8e1-2b17-4cf2-91c0-b83cef35d989', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='place', entity1_aliases=[], entity2_name='Ancient Greece', entity2_type='place', entity2_aliases=['early Greece'], canonical_name='Greece', similarity=0.7577589577043085, reasoning="Both mentions refer to the same geographic/civilizational entity (Greece) — one general name and one specifying the ancient/classical period. They are not distinct entity types or separate polities; they denote the same place/civilization, with 'Ancient Greece' a temporal specification of Greece. For canonical name choose the broader/common modern label 'Greece' unless period-specific tagging required.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 439945, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='66e6d2dc-314a-4ef9-938b-acdab78f0695', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='place', entity1_aliases=['early Greece', 'Ancient Greece'], entity2_name='Greek world', entity2_type='place', entity2_aliases=[], canonical_name='Greece', similarity=0.748914825038006, reasoning="Both names refer to the same geographic-cultural sphere composed of Greek city-states. 'Greece' and 'Greek world' are not distinct historical entities in this context but two ways to refer to the same region/cultural-political sphere.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 439962, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='ffb35f65-3715-4800-aaea-22840f4f44a3', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='place', entity1_aliases=['Ancient Greece', 'early Greece', 'Greek world'], entity2_name='Ancient Greece', entity2_type='place', entity2_aliases=['early Greece'], canonical_name='Ancient Greece', similarity=0.7387633459994754, reasoning="Both mentions denote the same geographic and cultural entity (Greece) in a historical context. 'Ancient Greece' specifies the historical period but refers to the same region/civilization as 'Greece' in the descriptions (city-states like Athens and Sparta). They are not distinct entity types and should be merged with the historically specific name as canonical if desired.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 439977, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='c380b76a-d4f5-4dd8-9d92-656922fa9f26', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='place', entity1_aliases=['Ancient Greece', 'early Greece', 'Greek world'], entity2_name='Ancient Greece', entity2_type='place', entity2_aliases=['early Greece'], canonical_name='Ancient Greece', similarity=0.7146713807749214, reasoning="Both mentions refer to the same geographical/cultural entity (Greece) with one label specifying the historical period ('Ancient Greece'). They are not distinct entities for the purpose of place normalization here but temporal subset vs general name — in many KG tasks these would be merged if entities are places rather than time-specific. Given descriptions both denote the region/civilization of Greece (classical/early period) and the more general 'Greece' entry encompasses the same region including city-states like Athens and Sparta.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 439994, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='9f916f20-163a-4504-908e-310664f9ac76', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='place', entity1_aliases=['Ancient Greece', 'early Greece', 'Greek world'], entity2_name='Greek peninsula', entity2_type='place', entity2_aliases=[], canonical_name='Greece', similarity=0.6786989615136242, reasoning="'Greece' (region of city-states including Athens) and 'Greek peninsula' (region invaded by the Hellenes) refer to the same geographic/historical region. Both denote the territory of the Greeks; descriptions are consistent aspects of the same place rather than distinct entities.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 440011, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='f3dba612-b6d9-4fab-9d7b-4cd5f7162bf5', graph_name='book3_ch2', merge_type='llm', entity1_name='ancient Greece', entity1_type='place', entity1_aliases=[], entity2_name='early Greece', entity2_type='place', entity2_aliases=[], canonical_name='ancient Greece', similarity=0.7134244990522067, reasoning="Both mentions refer to the same geographical/historical region of Greece in broad terms (ancient/early Greece). They are not distinct entities but variant phrasings of the same place/civilization period, so they should be merged. Canonical name chosen as the more common term 'ancient Greece'.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 437557, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='0050c21b-b641-4e41-81f4-ae4bb8a545e0', graph_name='book3_ch2', merge_type='rule', entity1_name='Greece', entity1_type='polity', entity1_aliases=['Greek'], entity2_name='Greece', entity2_type='polity', entity2_aliases=['archaic Greece', 'classical Greece'], canonical_name='Greece', similarity=None, reasoning='', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 437634, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='27efee67-6376-413a-9b86-959e0e9c27e4', graph_name='book3_ch2', merge_type='rule', entity1_name='Greece', entity1_type='polity', entity1_aliases=[], entity2_name='Greece', entity2_type='polity', entity2_aliases=['Greek', 'archaic Greece', 'classical Greece'], canonical_name='Greece', similarity=None, reasoning='', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 437785, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='1061f411-f2f4-488e-a060-c99d4148a5d7', graph_name='book3_ch2', merge_type='rule', entity1_name='Greece', entity1_type='polity', entity1_aliases=[], entity2_name='Greece', entity2_type='polity', entity2_aliases=['archaic Greece', 'Greek', 'classical Greece'], canonical_name='Greece', similarity=None, reasoning='', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 437863, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='90d50a9e-b250-4e66-8152-7bd8b9615834', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='polity', entity1_aliases=[], entity2_name='Greeks', entity2_type='polity', entity2_aliases=['Greek', 'Greek world', 'classical Greece', 'Hellenes'], canonical_name='Ancient Greece', similarity=0.6726881688901852, reasoning="Both mentions refer to the same historical entity: the civilization/people/polity of ancient Greece (the Greeks). Entity 1 is a general label 'Greece' and Entity 2 describes the Greeks (Hellenes), their society, city-states, and culture. These are not distinct entities but two ways of referring to the same historical polity/civilization.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 441201, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='b3a58953-0658-47f5-b889-a7634f346a54', graph_name='book3_ch2', merge_type='llm', entity1_name='Ancient Greece', entity1_type='polity', entity1_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Hellenes'], entity2_name='Greeks', entity2_type='polity', entity2_aliases=['Greek', 'Greek world', 'classical Greece', 'Hellenes'], canonical_name='Greece (ancient)', similarity=0.6624532484754085, reasoning="Both mentions refer to the same historical polity/civilization: the ancient Greeks/Greek world (classical Greece) described as a civilization of city-states and their people. Entity 1 is a general label ('Greece') and Entity 2 ('Greeks' with aliases) clearly denotes the same ancient Greek civilization/people. They are not distinct entities by type or scope here and should be merged under the common canonical name 'Greece (ancient)' to avoid ambiguity with modern Greece.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 441220, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='375ed3cd-92f1-446e-9dfd-398f128bd8c8', graph_name='book3_ch2', merge_type='llm', entity1_name='Greek society', entity1_type='polity', entity1_aliases=['Greek thought'], entity2_name='Ancient Greece', entity2_type='polity', entity2_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Hellenes'], canonical_name='Ancient Greece', similarity=0.7582447313213809, reasoning="Both entries refer to the same broad historical entity: the society/civilization of ancient Greece characterized by rational enquiry, philosophy, city-states, and cultural practices. 'Greek society' is a descriptive label for the social/cultural aspect of Ancient Greece but not a distinct entity from 'Ancient Greece' as a polity/civilization in this context. They should be merged with Ancient Greece as the canonical name.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 441256, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='07967725-4b09-41e5-b8be-1d78b96436e3', graph_name='book3_ch2', merge_type='llm', entity1_name='Ancient Greece', entity1_type='polity', entity1_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Greek thought', 'Hellenes'], entity2_name='Ancient Greece', entity2_type='polity', entity2_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Hellenes'], canonical_name='Ancient Greece', similarity=0.6580077453627963, reasoning="Both refer to the same historical polity/civilization: the society/culture of ancient Greeks. 'Greek society' is a descriptive phrase for the social/cultural entity covered by 'Ancient Greece' and is not a distinct polity. Therefore they should be merged, with 'Ancient Greece' as the canonical name.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 441276, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='ce1c2e06-f25e-445e-9c7e-710eca5b2aae', graph_name='book3_ch2', merge_type='rule', entity1_name='Greeks', entity1_type='polity', entity1_aliases=[], entity2_name='Ancient Greece', entity2_type='polity', entity2_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Greek thought', 'Hellenes'], canonical_name='Ancient Greece', similarity=None, reasoning='', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 442006, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='f10353da-9612-4382-92dd-6245f67a6f83', graph_name='book3_ch2', merge_type='rule', entity1_name='Greece', entity1_type='place', entity1_aliases=[], entity2_name='Greece', entity2_type='place', entity2_aliases=['Greek peninsula', 'early Greece', 'Ancient Greece', 'Greek world'], canonical_name='Greece', similarity=None, reasoning='', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 442156, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='8b0f9dc3-2840-4f14-8dc8-c1fbfa630359', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='polity', entity1_aliases=['ancient Greece'], entity2_name='Ancient Greece', entity2_type='polity', entity2_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Greek thought', 'Hellenes'], canonical_name='Ancient Greece', similarity=0.8307911208969361, reasoning='Both entries describe the same polity: the civilization/political entity of ancient Greece (classical Greek world). Names and aliases overlap (Greece vs Ancient Greece) and descriptions match. They are not distinct entities by period or aspect in the given data, so they should be merged.', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 442306, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='88e262ba-8ab9-46da-ba54-6314d711b3b0', graph_name='book3_ch2', merge_type='llm', entity1_name='Ancient Greece', entity1_type='polity', entity1_aliases=['Greeks', 'classical Greece', 'Greek world', 'Greek', 'Greek thought', 'Hellenes'], entity2_name='Greece', entity2_type='polity', entity2_aliases=['archaic Greece', 'Greek', 'classical Greece'], canonical_name='Greece', similarity=0.718661701418887, reasoning="Both entity entries describe the same polity: the civilization/political entity of ancient Greece (including classical/archaic periods and geographic extent). The differences are in phrasing and emphasis but not in identity. Therefore they should be merged. The most canonical/common name is the simple name 'Greece'.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 442323, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='46d249e3-d72e-49ad-b0ed-61009b1c7894', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='polity', entity1_aliases=['Greeks', 'archaic Greece', 'Greek world', 'classical Greece', 'Greek', 'Greek thought', 'Hellenes'], entity2_name='Ancient Greece', entity2_type='polity', entity2_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Greek thought', 'Hellenes'], canonical_name='Ancient Greece', similarity=0.7123185205279625, reasoning="Both entries clearly refer to the same historical polity/civilization: ancient Greece (the Greek world, classical Greece). The names and descriptions overlap and describe the same society/civilization. Canonical name chosen as the most common concise form 'Ancient Greece'.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 442344, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='ff89c228-53fa-44dd-8a3c-e49ea30ca150', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='polity', entity1_aliases=['Greeks', 'archaic Greece', 'Greek world', 'classical Greece', 'Greek', 'Greek thought', 'Hellenes'], entity2_name='Ancient Greece', entity2_type='polity', entity2_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Greek thought', 'Hellenes'], canonical_name='Ancient Greece', similarity=0.7077778895355986, reasoning='Both entries refer to the same historical polity/civilization: ancient Greece (the Greek city-state civilization and culture). Descriptions and aliases overlap and describe the same entity.', created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 442366, tzinfo=datetime.timezone.utc)),
 KGMergeDecision(id='8539be2e-c364-4fb5-9694-934ddb4dcff1', graph_name='book3_ch2', merge_type='llm', entity1_name='Greece', entity1_type='polity', entity1_aliases=['Greeks', 'archaic Greece', 'Greek world', 'classical Greece', 'Greek', 'Greek thought', 'Hellenes'], entity2_name='Ancient Greece', entity2_type='polity', entity2_aliases=['Greeks', 'Greek', 'Greek world', 'classical Greece', 'Greek thought', 'Hellenes'], canonical_name='Ancient Greece', similarity=0.6840516181501365, reasoning="Both entries refer to the same historical polity/civilization: the Greek world of antiquity. 'Greece' here is the general name and 'Ancient Greece' is the specific historical form; the descriptions match. They are not distinct entities in this context and should be merged under the common historical name.", created_at=datetime.datetime(2026, 3, 14, 23, 53, 0, 442389, tzinfo=datetime.timezone.utc)),

In [23]:
greece_merges_ch2[1].__dict__

{'id': 'ebd376ed-a222-4705-a716-581c432bf03a',
 'graph_name': 'book3_ch2',
 'merge_type': 'llm',
 'entity1_name': 'early Greece',
 'entity1_type': 'polity',
 'entity1_aliases': [],
 'entity2_name': 'Greeks',
 'entity2_type': 'polity',
 'entity2_aliases': ['Hellenes'],
 'canonical_name': 'Greeks (early Greece)',
 'similarity': 0.7045108821057713,
 'reasoning': "Both mentions refer to the same broad historical entity: the Greeks/early Greek civilization in the archaic period (before and around 500 BC). 'early Greece' describes the society and colonizing phase of the Greeks, while 'Greeks' (Hellenes) is the people themselves; here both clearly point to the same cultural-political group in ancient Greece. They are not distinct entities (one is not a specific subgroup or different polity).",
 'created_at': datetime.datetime(2026, 3, 14, 23, 53, 0, 437003, tzinfo=datetime.timezone.utc)}

In [20]:
greece_merges_ch2_df = pd.DataFrame([m.__dict__ for m in greece_merges_ch2])

In [22]:
greece_merges_ch2_df['merge_type'].value_counts()

merge_type
llm     22
rule     9
Name: count, dtype: int64